/**
 * 数据模块 - CET-4核心词汇 & 英文阅读文章
 */

// ===== CET-4 核心词汇（精选200+词）=====
const CET4_WORDS = [
  { word: "abandon", phonetic: "/əˈbændən/", pos: "v.", meaning: "放弃；遗弃", example: "He abandoned his car in the snow." },
  { word: "ability", phonetic: "/əˈbɪləti/", pos: "n.", meaning: "能力；才能", example: "She has the ability to learn quickly." },
  { word: "abroad", phonetic: "/əˈbrɔːd/", pos: "adv.", meaning: "在国外；到国外", example: "He plans to study abroad next year." },
  { word: "absent", phonetic: "/ˈæbsənt/", pos: "adj.", meaning: "缺席的；不在的", example: "Why were you absent from class?" },
  { word: "absolute", phonetic: "/ˈæbsəluːt/", pos: "adj.", meaning: "绝对的；完全的", example: "I have absolute confidence in you." },
  { word: "absorb", phonetic: "/əbˈzɔːb/", pos: "v.", meaning: "吸收；吸引", example: "Plants absorb sunlight for energy." },
  { word: "abstract", phonetic: "/ˈæbstrækt/", pos: "adj.", meaning: "抽象的", example: "Love is an abstract concept." },
  { word: "academic", phonetic: "/ˌækəˈdemɪk/", pos: "adj.", meaning: "学术的；学院的", example: "She has excellent academic records." },
  { word: "accept", phonetic: "/əkˈsept/", pos: "v.", meaning: "接受；同意", example: "Please accept my sincere apology." },
  { word: "access", phonetic: "/ˈækses/", pos: "n.", meaning: "进入；访问；通路", example: "Students have access to the library." },
  { word: "accident", phonetic: "/ˈæksɪdənt/", pos: "n.", meaning: "事故；意外", example: "The accident happened on a rainy night." },
  { word: "account", phonetic: "/əˈkaʊnt/", pos: "n.", meaning: "账户；描述", example: "He gave a detailed account of the event." },
  { word: "accurate", phonetic: "/ˈækjərət/", pos: "adj.", meaning: "准确的；精确的", example: "The clock keeps accurate time." },
  { word: "achieve", phonetic: "/əˈtʃiːv/", pos: "v.", meaning: "实现；达到", example: "She achieved her goal of becoming a doctor." },
  { word: "acquire", phonetic: "/əˈkwaɪər/", pos: "v.", meaning: "获得；取得", example: "He acquired a new skill through practice." },
  { word: "actual", phonetic: "/ˈæktʃuəl/", pos: "adj.", meaning: "实际的；真实的", example: "The actual cost was higher than expected." },
  { word: "adapt", phonetic: "/əˈdæpt/", pos: "v.", meaning: "适应；改编", example: "Children adapt to new environments quickly." },
  { word: "address", phonetic: "/əˈdres/", pos: "n./v.", meaning: "地址；演讲；解决", example: "Please write your address clearly." },
  { word: "adequate", phonetic: "/ˈædɪkwət/", pos: "adj.", meaning: "足够的；适当的", example: "We need adequate food for the trip." },
  { word: "adjust", phonetic: "/əˈdʒʌst/", pos: "v.", meaning: "调整；调节", example: "I need to adjust the volume." },
  { word: "administration", phonetic: "/ədˌmɪnɪˈstreɪʃn/", pos: "n.", meaning: "管理；行政", example: "The new administration made many changes." },
  { word: "admire", phonetic: "/ədˈmaɪər/", pos: "v.", meaning: "钦佩；欣赏", example: "I admire your courage and determination." },
  { word: "admit", phonetic: "/ədˈmɪt/", pos: "v.", meaning: "承认；准许进入", example: "He admitted his mistake bravely." },
  { word: "adopt", phonetic: "/əˈdɒpt/", pos: "v.", meaning: "采用；收养", example: "They decided to adopt a child." },
  { word: "adult", phonetic: "/ˈædʌlt/", pos: "n./adj.", meaning: "成年人", example: "This movie is for adults only." },
  { word: "advanced", phonetic: "/ədˈvɑːnst/", pos: "adj.", meaning: "先进的；高级的", example: "She is in an advanced math class." },
  { word: "advantage", phonetic: "/ədˈvɑːntɪdʒ/", pos: "n.", meaning: "优势；有利条件", example: "Speaking English is a great advantage." },
  { word: "adventure", phonetic: "/ədˈventʃər/", pos: "n.", meaning: "冒险；奇遇", example: "The trip was a real adventure." },
  { word: "advertise", phonetic: "/ˈædvətaɪz/", pos: "v.", meaning: "做广告；宣传", example: "They advertise their products on TV." },
  { word: "advice", phonetic: "/ədˈvaɪs/", pos: "n.", meaning: "建议；忠告", example: "Can you give me some advice?" },
  { word: "affect", phonetic: "/əˈfekt/", pos: "v.", meaning: "影响；感动", example: "The weather affects my mood." },
  { word: "afford", phonetic: "/əˈfɔːd/", pos: "v.", meaning: "买得起；负担得起", example: "I can't afford a new car." },
  { word: "agency", phonetic: "/ˈeɪdʒənsi/", pos: "n.", meaning: "代理处；机构", example: "She works at a travel agency." },
  { word: "agenda", phonetic: "/əˈdʒendə/", pos: "n.", meaning: "议程；日程", example: "What's on the agenda for today?" },
  { word: "agent", phonetic: "/ˈeɪdʒənt/", pos: "n.", meaning: "代理人；特工", example: "Our agent will contact you soon." },
  { word: "agriculture", phonetic: "/ˈæɡrɪkʌltʃər/", pos: "n.", meaning: "农业", example: "Agriculture is the backbone of the economy." },
  { word: "ahead", phonetic: "/əˈhed/", pos: "adv.", meaning: "在前面；提前", example: "The road ahead is full of challenges." },
  { word: "aim", phonetic: "/eɪm/", pos: "n./v.", meaning: "目标；瞄准", example: "What is your aim in life?" },
  { word: "airline", phonetic: "/ˈeəlaɪn/", pos: "n.", meaning: "航空公司", example: "Which airline are you flying with?" },
  { word: "alarm", phonetic: "/əˈlɑːm/", pos: "n.", meaning: "警报；闹钟", example: "I set my alarm for six o'clock." },
  { word: "album", phonetic: "/ˈælbəm/", pos: "n.", meaning: "相册；专辑", example: "She showed me her photo album." },
  { word: "alcohol", phonetic: "/ˈælkəhɒl/", pos: "n.", meaning: "酒精", example: "He doesn't drink alcohol." },
  { word: "alert", phonetic: "/əˈlɜːt/", pos: "adj./v.", meaning: "警觉的；警告", example: "Stay alert while driving at night." },
  { word: "alike", phonetic: "/əˈlaɪk/", pos: "adj./adv.", meaning: "相似的；同样地", example: "The twins look very much alike." },
  { word: "alive", phonetic: "/əˈlaɪv/", pos: "adj.", meaning: "活着的；有活力的", example: "The bird is still alive." },
  { word: "allow", phonetic: "/əˈlaʊ/", pos: "v.", meaning: "允许；许可", example: "Smoking is not allowed here." },
  { word: "alone", phonetic: "/əˈləʊn/", pos: "adj./adv.", meaning: "单独的；独自", example: "She lives alone in the city." },
  { word: "along", phonetic: "/əˈlɒŋ/", pos: "prep./adv.", meaning: "沿着；一起", example: "We walked along the river." },
  { word: "alter", phonetic: "/ˈɔːltər/", pos: "v.", meaning: "改变；更改", example: "We need to alter our plans." },
  { word: "alternative", phonetic: "/ɔːlˈtɜːnətɪv/", pos: "n./adj.", meaning: "替代方案；可供选择的", example: "Is there an alternative route?" },
  { word: "amazing", phonetic: "/əˈmeɪzɪŋ/", pos: "adj.", meaning: "令人惊奇的", example: "The view from the top was amazing." },
  { word: "ambition", phonetic: "/æmˈbɪʃn/", pos: "n.", meaning: "雄心；野心", example: "Her ambition is to become a scientist." },
  { word: "amount", phonetic: "/əˈmaʊnt/", pos: "n.", meaning: "数量；总额", example: "A large amount of money was spent." },
  { word: "amuse", phonetic: "/əˈmjuːz/", pos: "v.", meaning: "逗乐；娱乐", example: "The clown amused the children." },
  { word: "analyze", phonetic: "/ˈænəlaɪz/", pos: "v.", meaning: "分析", example: "We need to analyze the data carefully." },
  { word: "ancient", phonetic: "/ˈeɪnʃənt/", pos: "adj.", meaning: "古代的；古老的", example: "They visited an ancient temple." },
  { word: "angle", phonetic: "/ˈæŋɡl/", pos: "n.", meaning: "角度；观点", example: "Look at it from a different angle." },
  { word: "announce", phonetic: "/əˈnaʊns/", pos: "v.", meaning: "宣布；宣告", example: "They announced the winner on TV." },
  { word: "annual", phonetic: "/ˈænjuəl/", pos: "adj.", meaning: "每年的；年度的", example: "The annual meeting is in December." },
  { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", pos: "v.", meaning: "预期；预料", example: "We anticipate a successful outcome." },
  { word: "anxious", phonetic: "/ˈæŋkʃəs/", pos: "adj.", meaning: "焦虑的；渴望的", example: "She felt anxious about the exam." },
  { word: "apart", phonetic: "/əˈpɑːt/", pos: "adv.", meaning: "分开；分离", example: "The two houses are far apart." },
  { word: "apology", phonetic: "/əˈpɒlədʒi/", pos: "n.", meaning: "道歉；歉意", example: "Please accept my apology." },
  { word: "apparent", phonetic: "/əˈpærənt/", pos: "adj.", meaning: "明显的；表面上的", example: "It was apparent that he was lying." },
  { word: "appeal", phonetic: "/əˈpiːl/", pos: "v./n.", meaning: "呼吁；吸引力", example: "The design has great appeal." },
  { word: "appear", phonetic: "/əˈpɪər/", pos: "v.", meaning: "出现；似乎", example: "She appeared at the door suddenly." },
  { word: "appetite", phonetic: "/ˈæpɪtaɪt/", pos: "n.", meaning: "食欲；欲望", example: "Exercise gives you a good appetite." },
  { word: "applaud", phonetic: "/əˈplɔːd/", pos: "v.", meaning: "鼓掌；称赞", example: "The audience applauded loudly." },
  { word: "apply", phonetic: "/əˈplaɪ/", pos: "v.", meaning: "申请；应用", example: "She applied for a scholarship." },
  { word: "appoint", phonetic: "/əˈpɔɪnt/", pos: "v.", meaning: "任命；指定", example: "He was appointed as manager." },
  { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", pos: "v.", meaning: "感激；欣赏", example: "I appreciate your help." },
  { word: "approach", phonetic: "/əˈprəʊtʃ/", pos: "v./n.", meaning: "接近；方法", example: "We need a new approach to the problem." },
  { word: "appropriate", phonetic: "/əˈprəʊpriət/", pos: "adj.", meaning: "适当的；合适的", example: "Wear appropriate clothes for the interview." },
  { word: "approve", phonetic: "/əˈpruːv/", pos: "v.", meaning: "批准；赞成", example: "My parents don't approve of my decision." },
  { word: "approximate", phonetic: "/əˈprɒksɪmət/", pos: "adj.", meaning: "近似的；大约的", example: "The approximate cost is 500 yuan." },
  { word: "arbitrary", phonetic: "/ˈɑːbɪtrəri/", pos: "adj.", meaning: "任意的；武断的", example: "His decision was completely arbitrary." },
  { word: "architect", phonetic: "/ˈɑːkɪtekt/", pos: "n.", meaning: "建筑师", example: "The architect designed a beautiful building." },
  { word: "area", phonetic: "/ˈeəriə/", pos: "n.", meaning: "区域；面积", example: "This area is known for its parks." },
  { word: "argue", phonetic: "/ˈɑːɡjuː/", pos: "v.", meaning: "争论；辩论", example: "They argue about money all the time." },
  { word: "arise", phonetic: "/əˈraɪz/", pos: "v.", meaning: "出现；产生", example: "Problems may arise during the project." },
  { word: "arrange", phonetic: "/əˈreɪndʒ/", pos: "v.", meaning: "安排；排列", example: "I'll arrange a meeting for tomorrow." },
  { word: "arrest", phonetic: "/əˈrest/", pos: "v./n.", meaning: "逮捕；阻止", example: "The police arrested the suspect." },
  { word: "arrive", phonetic: "/əˈraɪv/", pos: "v.", meaning: "到达；抵达", example: "What time will you arrive?" },
  { word: "article", phonetic: "/ˈɑːtɪkl/", pos: "n.", meaning: "文章；物品", example: "I read an interesting article today." },
  { word: "artificial", phonetic: "/ˌɑːtɪˈfɪʃl/", pos: "adj.", meaning: "人工的；人造的", example: "The flowers are artificial but look real." },
  { word: "ashamed", phonetic: "/əˈʃeɪmd/", pos: "adj.", meaning: "羞耻的；惭愧的", example: "He felt ashamed of his behavior." },
  { word: "aspect", phonetic: "/ˈæspekt/", pos: "n.", meaning: "方面；层面", example: "We considered every aspect of the plan." },
  { word: "assess", phonetic: "/əˈses/", pos: "v.", meaning: "评估；评价", example: "We need to assess the risks." },
  { word: "assign", phonetic: "/əˈsaɪn/", pos: "v.", meaning: "分配；指派", example: "The teacher assigned homework to students." },
  { word: "assist", phonetic: "/əˈsɪst/", pos: "v.", meaning: "帮助；协助", example: "Can I assist you with anything?" },
  { word: "associate", phonetic: "/əˈsəʊʃieɪt/", pos: "v.", meaning: "联想；交往", example: "I associate summer with ice cream." },
  { word: "assume", phonetic: "/əˈsjuːm/", pos: "v.", meaning: "假设；认为", example: "I assume you know the rules." },
  { word: "assure", phonetic: "/əˈʃʊər/", pos: "v.", meaning: "保证；使确信", example: "I assure you everything will be fine." },
  { word: "athlete", phonetic: "/ˈæθliːt/", pos: "n.", meaning: "运动员", example: "He is a professional athlete." },
  { word: "atmosphere", phonetic: "/ˈætməsfɪər/", pos: "n.", meaning: "气氛；大气", example: "The restaurant has a cozy atmosphere." },
  { word: "attach", phonetic: "/əˈtætʃ/", pos: "v.", meaning: "附上；连接", example: "Please attach your resume to the email." },
  { word: "attain", phonetic: "/əˈteɪn/", pos: "v.", meaning: "获得；达到", example: "She attained the highest score." },
  { word: "attempt", phonetic: "/əˈtempt/", pos: "v./n.", meaning: "尝试；企图", example: "He attempted to climb the mountain." },
  { word: "attend", phonetic: "/əˈtend/", pos: "v.", meaning: "出席；参加", example: "She attended the conference last week." },
  { word: "attitude", phonetic: "/ˈætɪtjuːd/", pos: "n.", meaning: "态度；看法", example: "His attitude toward work is excellent." },
  { word: "attract", phonetic: "/əˈtrækt/", pos: "v.", meaning: "吸引；引起", example: "The flower attracts many bees." },
  { word: "audience", phonetic: "/ˈɔːdiəns/", pos: "n.", meaning: "观众；听众", example: "The audience enjoyed the performance." },
  { word: "authority", phonetic: "/ɔːˈθɒrəti/", pos: "n.", meaning: "权威；权力", example: "He has no authority to make decisions." },
  { word: "automatic", phonetic: "/ˌɔːtəˈmætɪk/", pos: "adj.", meaning: "自动的", example: "The doors are automatic." },
  { word: "available", phonetic: "/əˈveɪləbl/", pos: "adj.", meaning: "可获得的；有空的", example: "Are tickets still available?" },
  { word: "average", phonetic: "/ˈævərɪdʒ/", pos: "n./adj.", meaning: "平均的；普通的", example: "The average temperature is 20 degrees." },
  { word: "avoid", phonetic: "/əˈvɔɪd/", pos: "v.", meaning: "避免；回避", example: "Try to avoid eating too much sugar." },
  { word: "award", phonetic: "/əˈwɔːd/", pos: "n./v.", meaning: "奖励；授予", example: "She won an award for her research." },
  { word: "aware", phonetic: "/əˈweər/", pos: "adj.", meaning: "意识到的；知道的", example: "Are you aware of the risks?" },
  { word: "balance", phonetic: "/ˈbæləns/", pos: "n./v.", meaning: "平衡；余额", example: "It's important to balance work and life." },
  { word: "ban", phonetic: "/bæn/", pos: "v./n.", meaning: "禁止；禁令", example: "Smoking is banned in public places." },
  { word: "base", phonetic: "/beɪs/", pos: "n./v.", meaning: "基础；以…为基础", example: "The company is based in Beijing." },
  { word: "basic", phonetic: "/ˈbeɪsɪk/", pos: "adj.", meaning: "基本的；基础的", example: "These are the basic rules of the game." },
  { word: "battery", phonetic: "/ˈbætəri/", pos: "n.", meaning: "电池", example: "My phone battery is running low." },
  { word: "bear", phonetic: "/beər/", pos: "v.", meaning: "承受；忍受", example: "I can't bear the pain anymore." },
  { word: "beat", phonetic: "/biːt/", pos: "v.", meaning: "打败；敲打", example: "Our team beat them in the final." },
  { word: "behave", phonetic: "/bɪˈheɪv/", pos: "v.", meaning: "表现；举止", example: "Please behave yourself at the dinner." },
  { word: "believe", phonetic: "/bɪˈliːv/", pos: "v.", meaning: "相信；认为", example: "I believe you can do it." },
  { word: "belong", phonetic: "/bɪˈlɒŋ/", pos: "v.", meaning: "属于", example: "This book belongs to the library." },
  { word: "benefit", phonetic: "/ˈbenɪfɪt/", pos: "n./v.", meaning: "利益；受益", example: "Exercise benefits your health." },
  { word: "besides", phonetic: "/bɪˈsaɪdz/", pos: "adv./prep.", meaning: "此外；除…之外", example: "Besides English, she speaks French." },
  { word: "betray", phonetic: "/bɪˈtreɪ/", pos: "v.", meaning: "背叛；出卖", example: "He would never betray his friends." },
  { word: "beyond", phonetic: "/bɪˈjɒnd/", pos: "prep.", meaning: "超过；在…那边", example: "The path goes beyond the hill." },
  { word: "biology", phonetic: "/baɪˈɒlədʒi/", pos: "n.", meaning: "生物学", example: "She studies biology at university." },
  { word: "blank", phonetic: "/blæŋk/", pos: "adj./n.", meaning: "空白的；空白", example: "Please fill in the blank spaces." },
  { word: "blood", phonetic: "/blʌd/", pos: "n.", meaning: "血液；血统", example: "Blood is thicker than water." },
  { word: "border", phonetic: "/ˈbɔːdər/", pos: "n./v.", meaning: "边界；接壤", example: "The river forms a natural border." },
  { word: "bother", phonetic: "/ˈbɒðər/", pos: "v.", meaning: "打扰；麻烦", example: "Sorry to bother you at this hour." },
  { word: "bottom", phonetic: "/ˈbɒtəm/", pos: "n.", meaning: "底部；底", example: "There's a hole at the bottom of the cup." },
  { word: "brain", phonetic: "/breɪn/", pos: "n.", meaning: "大脑；头脑", example: "The brain controls the whole body." },
  { word: "branch", phonetic: "/brɑːntʃ/", pos: "n.", meaning: "树枝；分支", example: "The bank has branches all over the city." },
  { word: "brand", phonetic: "/brænd/", pos: "n.", meaning: "品牌", example: "What's your favorite clothing brand?" },
  { word: "brave", phonetic: "/breɪv/", pos: "adj.", meaning: "勇敢的", example: "The brave soldier saved many lives." },
  { word: "breath", phonetic: "/breθ/", pos: "n.", meaning: "呼吸；气息", example: "Take a deep breath and relax." },
  { word: "brief", phonetic: "/briːf/", pos: "adj.", meaning: "简短的；简洁的", example: "Let me give you a brief introduction." },
  { word: "brilliant", phonetic: "/ˈbrɪliənt/", pos: "adj.", meaning: "杰出的；灿烂的", example: "That's a brilliant idea!" },
  { word: "budget", phonetic: "/ˈbʌdʒɪt/", pos: "n./v.", meaning: "预算", example: "We need to stick to our budget." },
  { word: "burden", phonetic: "/ˈbɜːdn/", pos: "n.", meaning: "负担；重担", example: "I don't want to be a burden to you." },
  { word: "burst", phonetic: "/bɜːst/", pos: "v.", meaning: "爆发；破裂", example: "The balloon burst with a loud noise." },
  { word: "calculate", phonetic: "/ˈkælkjuleɪt/", pos: "v.", meaning: "计算；估计", example: "Let me calculate the total cost." },
  { word: "calm", phonetic: "/kɑːm/", pos: "adj./v.", meaning: "平静的；使平静", example: "Please stay calm in an emergency." },
  { word: "campaign", phonetic: "/kæmˈpeɪn/", pos: "n.", meaning: "运动；战役", example: "They launched a campaign against pollution." },
  { word: "cancel", phonetic: "/ˈkænsl/", pos: "v.", meaning: "取消；撤销", example: "The flight was canceled due to weather." },
  { word: "candidate", phonetic: "/ˈkændɪdət/", pos: "n.", meaning: "候选人", example: "She is the best candidate for the job." },
  { word: "capable", phonetic: "/ˈkeɪpəbl/", pos: "adj.", meaning: "有能力的", example: "He is capable of doing the work." },
  { word: "capacity", phonetic: "/kəˈpæsəti/", pos: "n.", meaning: "容量；能力", example: "The hall has a capacity of 500 people." },
  { word: "capital", phonetic: "/ˈkæpɪtl/", pos: "n.", meaning: "首都；资本", example: "Beijing is the capital of China." },
  { word: "career", phonetic: "/kəˈrɪər/", pos: "n.", meaning: "职业；生涯", example: "She started her career as a teacher." },
  { word: "careful", phonetic: "/ˈkeəfl/", pos: "adj.", meaning: "仔细的；小心的", example: "Be careful when crossing the street." },
  { word: "cargo", phonetic: "/ˈkɑːɡəʊ/", pos: "n.", meaning: "货物", example: "The ship carries cargo to different ports." },
  { word: "carry", phonetic: "/ˈkæri/", pos: "v.", meaning: "携带；搬运", example: "Can you carry this bag for me?" },
  { word: "case", phonetic: "/keɪs/", pos: "n.", meaning: "情况；案例", example: "In that case, we should leave now." },
  { word: "catalog", phonetic: "/ˈkætəlɒɡ/", pos: "n.", meaning: "目录", example: "You can find it in the product catalog." },
  { word: "category", phonetic: "/ˈkætəɡəri/", pos: "n.", meaning: "类别；范畴", example: "Books are sorted by category." },
  { word: "cause", phonetic: "/kɔːz/", pos: "n./v.", meaning: "原因；引起", example: "What caused the accident?" },
  { word: "caution", phonetic: "/ˈkɔːʃn/", pos: "n./v.", meaning: "谨慎；警告", example: "Drive with caution on icy roads." },
  { word: "celebrate", phonetic: "/ˈselɪbreɪt/", pos: "v.", meaning: "庆祝", example: "We celebrate New Year with family." },
  { word: "ceremony", phonetic: "/ˈserəməni/", pos: "n.", meaning: "仪式；典礼", example: "The wedding ceremony was beautiful." },
  { word: "certain", phonetic: "/ˈsɜːtn/", pos: "adj.", meaning: "确定的；某个", example: "I am certain that he will come." },
  { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", pos: "n./v.", meaning: "挑战", example: "Learning a new language is a challenge." },
  { word: "champion", phonetic: "/ˈtʃæmpiən/", pos: "n.", meaning: "冠军", example: "She became the world champion." },
  { word: "channel", phonetic: "/ˈtʃænl/", pos: "n.", meaning: "频道；渠道", example: "Change the channel, please." },
  { word: "character", phonetic: "/ˈkærəktər/", pos: "n.", meaning: "性格；角色", example: "He has a strong character." },
  { word: "charge", phonetic: "/tʃɑːdʒ/", pos: "v./n.", meaning: "充电；收费；负责", example: "Who is in charge of this project?" },
  { word: "chart", phonetic: "/tʃɑːt/", pos: "n.", meaning: "图表", example: "Look at the chart on the wall." },
  { word: "cheat", phonetic: "/tʃiːt/", pos: "v.", meaning: "欺骗；作弊", example: "Don't cheat on the exam." },
  { word: "chemical", phonetic: "/ˈkemɪkl/", pos: "adj./n.", meaning: "化学的；化学品", example: "Some chemicals are dangerous." },
  { word: "chief", phonetic: "/tʃiːf/", pos: "adj./n.", meaning: "主要的；首领", example: "He is the chief editor of the magazine." },
  { word: "choice", phonetic: "/tʃɔɪs/", pos: "n.", meaning: "选择", example: "You have to make a choice." },
  { word: "circuit", phonetic: "/ˈsɜːkɪt/", pos: "n.", meaning: "电路；环道", example: "The circuit is broken." },
  { word: "circumstance", phonetic: "/ˈsɜːkəmstəns/", pos: "n.", meaning: "情况；环境", example: "Under no circumstances should you give up." },
  { word: "citizen", phonetic: "/ˈsɪtɪzn/", pos: "n.", meaning: "公民；市民", example: "Every citizen has the right to vote." },
  { word: "civil", phonetic: "/ˈsɪvl/", pos: "adj.", meaning: "公民的；文明的", example: "They fought for civil rights." },
  { word: "claim", phonetic: "/kleɪm/", pos: "v./n.", meaning: "声称；要求", example: "He claims to be a doctor." },
  { word: "classic", phonetic: "/ˈklæsɪk/", pos: "adj./n.", meaning: "经典的", example: "This is a classic novel." },
  { word: "climate", phonetic: "/ˈklaɪmət/", pos: "n.", meaning: "气候", example: "The climate here is very mild." },
  { word: "climb", phonetic: "/klaɪm/", pos: "v.", meaning: "攀登；爬", example: "They climbed to the top of the mountain." },
  { word: "clinic", phonetic: "/ˈklɪnɪk/", pos: "n.", meaning: "诊所", example: "She goes to the clinic every week." },
  { word: "clue", phonetic: "/kluː/", pos: "n.", meaning: "线索", example: "The detective found an important clue." },
  { word: "coast", phonetic: "/kəʊst/", pos: "n.", meaning: "海岸", example: "We drove along the coast." },
  { word: "code", phonetic: "/kəʊd/", pos: "n.", meaning: "代码；密码", example: "What's the zip code for this area?" },
  { word: "colleague", phonetic: "/ˈkɒliːɡ/", pos: "n.", meaning: "同事", example: "My colleague helped me with the project." },
  { word: "collect", phonetic: "/kəˈlekt/", pos: "v.", meaning: "收集；聚集", example: "She collects stamps as a hobby." },
  { word: "combine", phonetic: "/kəmˈbaɪn/", pos: "v.", meaning: "结合；联合", example: "We should combine our efforts." },
  { word: "comfort", phonetic: "/ˈkʌmfət/", pos: "n./v.", meaning: "舒适；安慰", example: "The chair provides great comfort." },
  { word: "command", phonetic: "/kəˈmɑːnd/", pos: "v./n.", meaning: "命令；指挥", example: "The officer commanded the soldiers." },
  { word: "comment", phonetic: "/ˈkɒment/", pos: "n./v.", meaning: "评论；意见", example: "Can I make a comment?" },
  { word: "commerce", phonetic: "/ˈkɒmɜːs/", pos: "n.", meaning: "商业；贸易", example: "E-commerce is growing rapidly." },
  { word: "commission", phonetic: "/kəˈmɪʃn/", pos: "n.", meaning: "佣金；委员会", example: "He earns commission on every sale." },
  { word: "commit", phonetic: "/kəˈmɪt/", pos: "v.", meaning: "犯（罪）；承诺", example: "He committed a serious crime." },
  { word: "committee", phonetic: "/kəˈmɪti/", pos: "n.", meaning: "委员会", example: "The committee will meet tomorrow." },
  { word: "common", phonetic: "/ˈkɒmən/", pos: "adj.", meaning: "常见的；共同的", example: "This is a common mistake." },
  { word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", pos: "v.", meaning: "交流；沟通", example: "We communicate through emails." },
  { word: "community", phonetic: "/kəˈmjuːnəti/", pos: "n.", meaning: "社区；群体", example: "She is active in the local community." },
  { word: "compare", phonetic: "/kəmˈpeər/", pos: "v.", meaning: "比较；对比", example: "Let's compare the two options." },
  { word: "compete", phonetic: "/kəmˈpiːt/", pos: "v.", meaning: "竞争；比赛", example: "They compete for the championship." },
  { word: "complain", phonetic: "/kəmˈpleɪn/", pos: "v.", meaning: "抱怨；投诉", example: "She complains about everything." },
  { word: "complete", phonetic: "/kəmˈpliːt/", pos: "v./adj.", meaning: "完成；完整的", example: "The project is now complete." },
  { word: "complex", phonetic: "/ˈkɒmpleks/", pos: "adj.", meaning: "复杂的", example: "This is a complex problem." },
  { word: "concept", phonetic: "/ˈkɒnsept/", pos: "n.", meaning: "概念；观念", example: "The concept is easy to understand." },
  { word: "concern", phonetic: "/kənˈsɜːn/", pos: "v./n.", meaning: "关心；担忧", example: "This concerns everyone." },
  { word: "conclude", phonetic: "/kənˈkluːd/", pos: "v.", meaning: "得出结论；结束", example: "We concluded the meeting at noon." },
  { word: "concrete", phonetic: "/ˈkɒnkriːt/", pos: "adj./n.", meaning: "具体的；混凝土", example: "Give me a concrete example." },
  { word: "condition", phonetic: "/kənˈdɪʃn/", pos: "n.", meaning: "条件；状况", example: "The car is in good condition." },
  { word: "conduct", phonetic: "/kənˈdʌkt/", pos: "v./n.", meaning: "进行；行为", example: "They conducted a survey." },
  { word: "conference", phonetic: "/ˈkɒnfərəns/", pos: "n.", meaning: "会议；讨论会", example: "She attended a conference in London." },
  { word: "confidence", phonetic: "/ˈkɒnfɪdəns/", pos: "n.", meaning: "信心；信任", example: "I have confidence in your ability." },
  { word: "confirm", phonetic: "/kənˈfɜːm/", pos: "v.", meaning: "确认；证实", example: "Please confirm your reservation." },
  { word: "conflict", phonetic: "/ˈkɒnflɪkt/", pos: "n.", meaning: "冲突；矛盾", example: "There was a conflict between them." },
  { word: "confront", phonetic: "/kənˈfrʌnt/", pos: "v.", meaning: "面对；对抗", example: "We must confront the problem." },
  { word: "confuse", phonetic: "/kənˈfjuːz/", pos: "v.", meaning: "使困惑；混淆", example: "The instructions confused me." },
  { word: "connect", phonetic: "/kəˈnekt/", pos: "v.", meaning: "连接；联系", example: "The bridge connects the two cities." },
  { word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", pos: "n.", meaning: "后果；结果", example: "You must face the consequences." },
  { word: "consider", phonetic: "/kənˈsɪdər/", pos: "v.", meaning: "考虑；认为", example: "Please consider my offer." },
  { word: "consist", phonetic: "/kənˈsɪst/", pos: "v.", meaning: "由…组成", example: "Water consists of hydrogen and oxygen." },
  { word: "constant", phonetic: "/ˈkɒnstənt/", pos: "adj.", meaning: "不断的；恒定的", example: "There is a constant need for water." },
  { word: "construct", phonetic: "/kənˈstrʌkt/", pos: "v.", meaning: "建造；构造", example: "They constructed a new bridge." },
  { word: "consult", phonetic: "/kənˈsʌlt/", pos: "v.", meaning: "咨询；查阅", example: "You should consult a doctor." },
  { word: "consume", phonetic: "/kənˈsjuːm/", pos: "v.", meaning: "消耗；消费", example: "The car consumes a lot of fuel." },
  { word: "contact", phonetic: "/ˈkɒntækt/", pos: "v./n.", meaning: "联系；接触", example: "Please contact me by email." },
  { word: "contain", phonetic: "/kənˈteɪn/", pos: "v.", meaning: "包含；容纳", example: "The box contains old photos." },
  { word: "contest", phonetic: "/ˈkɒntest/", pos: "n./v.", meaning: "比赛；竞争", example: "She won the speech contest." },
  { word: "context", phonetic: "/ˈkɒntekst/", pos: "n.", meaning: "上下文；背景", example: "Understand the word in context." },
  { word: "contract", phonetic: "/ˈkɒntrækt/", pos: "n./v.", meaning: "合同；收缩", example: "Both parties signed the contract." },
  { word: "contradict", phonetic: "/ˌkɒntrəˈdɪkt/", pos: "v.", meaning: "反驳；矛盾", example: "His actions contradict his words." },
  { word: "contribute", phonetic: "/kənˈtrɪbjuːt/", pos: "v.", meaning: "贡献；捐献", example: "Everyone contributed to the gift." },
  { word: "control", phonetic: "/kənˈtrəʊl/", pos: "v./n.", meaning: "控制；管理", example: "Try to control your temper." },
  { word: "convenient", phonetic: "/kənˈviːniənt/", pos: "adj.", meaning: "方便的；便利的", example: "Is this time convenient for you?" },
  { word: "convention", phonetic: "/kənˈvenʃn/", pos: "n.", meaning: "惯例；大会", example: "It's a social convention to shake hands." },
  { word: "convince", phonetic: "/kənˈvɪns/", pos: "v.", meaning: "说服；使确信", example: "She convinced me to try again." },
  { word: "cooperate", phonetic: "/kəʊˈɒpəreɪt/", pos: "v.", meaning: "合作；协作", example: "The two companies cooperated on the project." },
  { word: "copper", phonetic: "/ˈkɒpər/", pos: "n.", meaning: "铜", example: "Copper is a good conductor." },
  { word: "copyright", phonetic: "/ˈkɒpiraɪt/", pos: "n.", meaning: "版权", example: "This material is protected by copyright." },
  { word: "corner", phonetic: "/ˈkɔːnər/", pos: "n.", meaning: "角落；转角", example: "The shop is on the corner." },
  { word: "corporate", phonetic: "/ˈkɔːpərət/", pos: "adj.", meaning: "公司的；法人的", example: "He works in a corporate environment." },
  { word: "correct", phonetic: "/kəˈrekt/", pos: "adj./v.", meaning: "正确的；纠正", example: "Your answer is correct." },
  { word: "cost", phonetic: "/kɒst/", pos: "n./v.", meaning: "花费；成本", example: "How much does it cost?" },
  { word: "council", phonetic: "/ˈkaʊnsl/", pos: "n.", meaning: "委员会；理事会", example: "The city council makes local laws." },
  { word: "count", phonetic: "/kaʊnt/", pos: "v.", meaning: "数；计数；重要", example: "Every vote counts." },
  { word: "country", phonetic: "/ˈkʌntri/", pos: "n.", meaning: "国家；乡村", example: "China is a beautiful country." },
  { word: "courage", phonetic: "/ˈkʌrɪdʒ/", pos: "n.", meaning: "勇气；胆量", example: "It takes courage to speak up." },
  { word: "course", phonetic: "/kɔːs/", pos: "n.", meaning: "课程；过程", example: "I signed up for a cooking course." },
  { word: "court", phonetic: "/kɔːt/", pos: "n.", meaning: "法庭；球场", example: "The case will go to court." },
  { word: "cover", phonetic: "/ˈkʌvər/", pos: "v./n.", meaning: "覆盖；封面", example: "The book has a beautiful cover." },
  { word: "crash", phonetic: "/kræʃ/", pos: "v./n.", meaning: "碰撞；坠毁", example: "The computer crashed again." },
  { word: "create", phonetic: "/kriˈeɪt/", pos: "v.", meaning: "创造；创作", example: "Artists create beautiful things." },
  { word: "creative", phonetic: "/kriˈeɪtɪv/", pos: "adj.", meaning: "有创造力的", example: "She has a creative mind." },
  { word: "credit", phonetic: "/ˈkredɪt/", pos: "n.", meaning: "信用；学分", example: "I used my credit card to pay." },
  { word: "crisis", phonetic: "/ˈkraɪsɪs/", pos: "n.", meaning: "危机", example: "The country is facing an economic crisis." },
  { word: "criticize", phonetic: "/ˈkrɪtɪsaɪz/", pos: "v.", meaning: "批评；评论", example: "Don't criticize others too harshly." },
  { word: "current", phonetic: "/ˈkʌrənt/", pos: "adj./n.", meaning: "当前的；潮流", example: "What's the current time?" },
  { word: "curious", phonetic: "/ˈkjʊəriəs/", pos: "adj.", meaning: "好奇的", example: "Children are naturally curious." },
  { word: "currency", phonetic: "/ˈkʌrənsi/", pos: "n.", meaning: "货币", example: "What currency do they use?" },
  { word: "custom", phonetic: "/ˈkʌstəm/", pos: "n.", meaning: "习俗；海关", example: "It's a local custom to give gifts." },
  { word: "customer", phonetic: "/ˈkʌstəmər/", pos: "n.", meaning: "顾客", example: "The customer is always right." },
  { word: "damage", phonetic: "/ˈdæmɪdʒ/", pos: "n./v.", meaning: "损害；损坏", example: "The storm caused great damage." },
  { word: "debate", phonetic: "/dɪˈbeɪt/", pos: "n./v.", meaning: "辩论；讨论", example: "They had a heated debate." },
  { word: "decade", phonetic: "/ˈdekeɪd/", pos: "n.", meaning: "十年", example: "Things have changed in the past decade." },
  { word: "decide", phonetic: "/dɪˈsaɪd/", pos: "v.", meaning: "决定", example: "It's up to you to decide." },
  { word: "declare", phonetic: "/dɪˈkleər/", pos: "v.", meaning: "宣布；声明", example: "He declared his support for the plan." },
  { word: "decline", phonetic: "/dɪˈklaɪn/", pos: "v./n.", meaning: "下降；拒绝", example: "Sales declined last month." },
  { word: "decorate", phonetic: "/ˈdekəreɪt/", pos: "v.", meaning: "装饰", example: "They decorated the room for the party." },
  { word: "decrease", phonetic: "/dɪˈkriːs/", pos: "v./n.", meaning: "减少；降低", example: "The temperature decreased at night." },
  { word: "defeat", phonetic: "/dɪˈfiːt/", pos: "v./n.", meaning: "击败；战胜", example: "Our team defeated the opponents." },
  { word: "defend", phonetic: "/dɪˈfend/", pos: "v.", meaning: "保卫；防守", example: "Soldiers defend their country." },
  { word: "define", phonetic: "/dɪˈfaɪn/", pos: "v.", meaning: "定义；解释", example: "How do you define success?" },
  { word: "degree", phonetic: "/dɪˈɡriː/", pos: "n.", meaning: "程度；学位", example: "She has a degree in chemistry." },
  { word: "delay", phonetic: "/dɪˈleɪ/", pos: "v./n.", meaning: "延迟；耽搁", example: "The flight was delayed by two hours." },
  { word: "deliver", phonetic: "/dɪˈlɪvər/", pos: "v.", meaning: "递送；交付", example: "The mail is delivered every morning." },
  { word: "demand", phonetic: "/dɪˈmɑːnd/", pos: "n./v.", meaning: "需求；要求", example: "There is a high demand for engineers." },
  { word: "depend", phonetic: "/dɪˈpend/", pos: "v.", meaning: "依赖；取决于", example: "It depends on the weather." },
  { word: "deposit", phonetic: "/dɪˈpɒzɪt/", pos: "n./v.", meaning: "存款；押金", example: "I need to deposit some money." },
  { word: "describe", phonetic: "/dɪˈskraɪb/", pos: "v.", meaning: "描述；描写", example: "Can you describe the scene?" },
  { word: "design", phonetic: "/dɪˈzaɪn/", pos: "n./v.", meaning: "设计", example: "She designs websites for a living." },
  { word: "desire", phonetic: "/dɪˈzaɪər/", pos: "n./v.", meaning: "渴望；欲望", example: "He has a strong desire to travel." },
  { word: "destroy", phonetic: "/dɪˈstrɔɪ/", pos: "v.", meaning: "破坏；摧毁", example: "The fire destroyed the entire building." },
  { word: "detail", phonetic: "/ˈdiːteɪl/", pos: "n.", meaning: "细节", example: "Please explain in detail." },
  { word: "detect", phonetic: "/dɪˈtekt/", pos: "v.", meaning: "发现；察觉", example: "The sensor can detect movement." },
  { word: "determine", phonetic: "/dɪˈtɜːmɪn/", pos: "v.", meaning: "决定；确定", example: "Hard work determines success." },
  { word: "develop", phonetic: "/dɪˈveləp/", pos: "v.", meaning: "发展；开发", example: "The city developed rapidly." },
  { word: "device", phonetic: "/dɪˈvaɪs/", pos: "n.", meaning: "设备；装置", example: "This is a useful device." },
  { word: "devote", phonetic: "/dɪˈvəʊt/", pos: "v.", meaning: "奉献；致力于", example: "She devoted her life to teaching." }
];

// ===== 英文阅读文章（原创短篇）=====
const ARTICLES = [
  {
    id: 1,
    title: "The Little Garden",
    level: "Beginner",
    sentences: [
      { en: "There was a little girl named Lily who loved flowers very much.", zh: "有一个叫莉莉的小女孩，她非常喜欢花。" },
      { en: "Every morning, she would run to her small garden behind the house.", zh: "每天早上，她都会跑到屋后的小花园里。" },
      { en: "The garden was not big, but it was full of colors.", zh: "花园不大，但色彩缤纷。" },
      { en: "Red roses, yellow sunflowers, and purple lavender grew side by side.", zh: "红玫瑰、黄向日葵和紫薰衣草并排生长着。" },
      { en: "Lily watered them every day and talked to them gently.", zh: "莉莉每天都给它们浇水，温柔地和它们说话。" },
      { en: "One day, a small bird came to visit the garden.", zh: "有一天，一只小鸟来到了花园。" },
      { en: "It sang a beautiful song on the branch of a tree.", zh: "它在树枝上唱了一首动听的歌。" },
      { en: "Lily was so happy that she danced with the music.", zh: "莉莉高兴得随着音乐跳起舞来。" },
      { en: "From that day on, the bird came every morning to sing.", zh: "从那天起，小鸟每天早上都来唱歌。" },
      { en: "The little garden became the happiest place in the world.", zh: "小花园成了世界上最快乐的地方。" }
    ]
  },
  {
    id: 2,
    title: "Tom and the Magic Book",
    level: "Beginner",
    sentences: [
      { en: "Tom was a curious boy who loved reading books.", zh: "汤姆是个爱读书的好奇男孩。" },
      { en: "One afternoon, he found an old book in the attic.", zh: "一天下午，他在阁楼里找到了一本旧书。" },
      { en: "The cover was dusty, but the pages were golden.", zh: "封面上布满灰尘，但书页是金色的。" },
      { en: "When he opened it, the letters began to glow.", zh: "当他打开书时，字母开始发光。" },
      { en: "Suddenly, he was inside the story!", zh: "突然间，他进入了故事里！" },
      { en: "He found himself in a forest full of talking animals.", zh: "他发现自己来到了一个满是会说话的动物的森林。" },
      { en: "A wise owl greeted him and showed him the way.", zh: "一只聪明的猫头鹰向他打招呼并给他指路。" },
      { en: "Together, they went on an amazing adventure.", zh: "他们一起经历了一场奇妙的冒险。" },
      { en: "When the adventure ended, Tom was back in his room.", zh: "冒险结束后，汤姆回到了自己的房间。" },
      { en: "He smiled and couldn't wait to read the next chapter.", zh: "他笑了笑，迫不及待地想读下一章。" }
    ]
  },
  {
    id: 3,
    title: "The Secret of the Sea",
    level: "Elementary",
    sentences: [
      { en: "Long ago, there was a small village by the sea.", zh: "很久以前，海边有一个小村庄。" },
      { en: "The villagers were all fishermen who depended on the ocean.", zh: "村民们都是渔民，靠大海为生。" },
      { en: "Every day, they sailed out to catch fish.", zh: "每天，他们都出海捕鱼。" },
      { en: "One day, a huge storm came without warning.", zh: "有一天，一场巨大的风暴毫无预兆地来了。" },
      { en: "The waves were as tall as mountains.", zh: "海浪像山一样高。" },
      { en: "The fishermen were afraid and did not know what to do.", zh: "渔民们很害怕，不知道该怎么办。" },
      { en: "An old man told them to follow the dolphins.", zh: "一位老人告诉他们跟着海豚走。" },
      { en: "The dolphins led them to a safe bay.", zh: "海豚把他们带到了一个安全的海湾。" },
      { en: "From that day, the villagers respected the sea and its creatures.", zh: "从那天起，村民们敬畏大海和它的生灵。" },
      { en: "They learned that nature always has secrets to share.", zh: "他们学会了自然总有秘密可以分享。" }
    ]
  },
  {
    id: 4,
    title: "Emma's First Day at School",
    level: "Beginner",
    sentences: [
      { en: "Emma was six years old and today was her first day at school.", zh: "艾玛六岁了，今天是她的第一天上学。" },
      { en: "She woke up early and put on her new uniform.", zh: "她早早起床，穿上了新校服。" },
      { en: "Her mother braided her hair and packed her lunch.", zh: "妈妈给她编了辫子，装好了午餐。" },
      { en: "At the school gate, Emma felt a little nervous.", zh: "在学校门口，艾玛感到有点紧张。" },
      { en: "But then a girl with a big smile walked up to her.", zh: "但随后一个笑容满面的女孩向她走来。" },
      { en: "Hi, I'm Sophie! Do you want to be friends?", zh: "嗨，我是苏菲！你想做朋友吗？" },
      { en: "Emma smiled and said yes happily.", zh: "艾玛笑了，开心地说好。" },
      { en: "They walked into the classroom together.", zh: "她们一起走进了教室。" },
      { en: "The teacher was kind and made everyone feel welcome.", zh: "老师很和蔼，让每个人都感到受欢迎。" },
      { en: "By the end of the day, Emma loved school.", zh: "到放学时，艾玛已经爱上了学校。" }
    ]
  },
  {
    id: 5,
    title: "The Brave Little Dog",
    level: "Elementary",
    sentences: [
      { en: "There was a small dog named Max who lived on a farm.", zh: "有一只叫麦克斯的小狗住在农场里。" },
      { en: "Max was small, but he was very brave.", zh: "麦克斯很小，但他非常勇敢。" },
      { en: "One night, a fox came close to the chicken coop.", zh: "一天晚上，一只狐狸靠近了鸡舍。" },
      { en: "All the other animals were sleeping.", zh: "其他动物都在睡觉。" },
      { en: "But Max heard the fox and started barking loudly.", zh: "但麦克斯听到了狐狸的声音，开始大声叫。" },
      { en: "The farmer woke up and came out with a lantern.", zh: "农夫醒了，提着灯笼出来了。" },
      { en: "The fox was scared and ran away into the dark.", zh: "狐狸被吓跑了，消失在黑暗中。" },
      { en: "The farmer patted Max and gave him a special treat.", zh: "农夫拍了拍麦克斯，给了他一份特别的奖励。" },
      { en: "From that night, all the animals respected little Max.", zh: "从那个晚上起，所有动物都尊敬小麦克斯了。" },
      { en: "Being brave is not about size, but about heart.", zh: "勇敢不在于体型大小，而在于内心。" }
    ]
  },
  {
    id: 6,
    title: "A Trip to the Mountains",
    level: "Elementary",
    sentences: [
      { en: "Last summer, my family went on a trip to the mountains.", zh: "去年夏天，我们一家去山里旅行。" },
      { en: "We drove for three hours to reach the foot of the mountain.", zh: "我们开了三个小时的车才到达山脚下。" },
      { en: "The air was fresh and cool, quite different from the city.", zh: "空气清新凉爽，和城市完全不同。" },
      { en: "We started climbing early in the morning.", zh: "我们一大早就开始爬山。" },
      { en: "Along the way, we saw many beautiful wildflowers.", zh: "一路上，我们看到了许多美丽的野花。" },
      { en: "My father told us the names of different trees.", zh: "爸爸告诉我们不同树木的名字。" },
      { en: "When we reached the top, the view was breathtaking.", zh: "当我们到达山顶时，风景令人叹为观止。" },
      { en: "We could see the whole valley below us.", zh: "我们可以看到下面整个山谷。" },
      { en: "We had a picnic and watched the sunset together.", zh: "我们野餐，一起看日落。" },
      { en: "It was the best trip we ever had.", zh: "这是我们最好的旅行。" }
    ]
  },
  {
    id: 7,
    title: "The Kind Baker",
    level: "Elementary",
    sentences: [
      { en: "In a small town, there lived a kind baker named Mr. Brown.", zh: "在一个小镇上，住着一位善良的面包师布朗先生。" },
      { en: "Every morning, he baked fresh bread and cakes.", zh: "每天早上，他都会烤新鲜的面包和蛋糕。" },
      { en: "His bakery was the most popular shop in town.", zh: "他的面包店是镇上最受欢迎的店铺。" },
      { en: "But what made him special was his kindness.", zh: "但让他特别的是他的善良。" },
      { en: "Every day, he gave free bread to poor children.", zh: "每天，他都给贫困的孩子免费面包。" },
      { en: "He never turned anyone away who was hungry.", zh: "他从不拒绝任何饥饿的人。" },
      { en: "One winter, a traveler came to his shop.", zh: "有一年冬天，一个旅行者来到他的店。" },
      { en: "He was cold and had no money for food.", zh: "他很冷，也没有钱买食物。" },
      { en: "Mr. Brown gave him warm soup and fresh bread.", zh: "布朗先生给了他热汤和新鲜面包。" },
      { en: "The traveler was so moved that he told everyone about the kind baker.", zh: "旅行者非常感动，把善良面包师的事告诉了所有人。" }
    ]
  },
  {
    id: 8,
    title: "The Lost Kitten",
    level: "Beginner",
    sentences: [
      { en: "One rainy evening, Sarah heard a soft cry outside.", zh: "一个下雨的傍晚，莎拉听到外面有微弱的哭声。" },
      { en: "She opened the door and found a tiny kitten.", zh: "她打开门，发现了一只小猫。" },
      { en: "The kitten was wet and shivering with cold.", zh: "小猫浑身湿透，冷得发抖。" },
      { en: "Sarah picked it up and brought it inside.", zh: "莎拉把它抱起来，带进了屋里。" },
      { en: "She wrapped it in a warm towel and gave it milk.", zh: "她用温暖的毛巾裹住它，给了它牛奶。" },
      { en: "The kitten purred and fell asleep in her arms.", zh: "小猫咕噜咕噜地叫着，在她怀里睡着了。" },
      { en: "The next day, Sarah made posters to find its owner.", zh: "第二天，莎拉做了海报寻找它的主人。" },
      { en: "But no one came to claim the kitten.", zh: "但没有人来认领这只小猫。" },
      { en: "So Sarah decided to keep it and named it Rainy.", zh: "于是莎拉决定收养它，取名叫小雨。" },
      { en: "They became the best of friends forever.", zh: "他们成了永远最好的朋友。" }
    ]
  },
  {
    id: 9,
    title: "The Magic Paintbrush",
    level: "Elementary",
    sentences: [
      { en: "Once upon a time, there was a poor boy named Jack.", zh: "从前，有一个叫杰克的穷男孩。" },
      { en: "He loved to draw but could not afford paint.", zh: "他喜欢画画，但买不起颜料。" },
      { en: "One night, an old man appeared in his dream.", zh: "一天晚上，一位老人出现在他的梦中。" },
      { en: "He gave Jack a magic paintbrush.", zh: "他给了杰克一支神奇的画笔。" },
      { en: "Whatever Jack painted with it came to life.", zh: "杰克用它画的一切都会变成真的。" },
      { en: "He painted food for hungry people and houses for the homeless.", zh: "他为饥饿的人画食物，为无家可归的人画房子。" },
      { en: "Soon, the king heard about the magic paintbrush.", zh: "很快，国王听说了这支神奇的画笔。" },
      { en: "He demanded Jack paint him mountains of gold.", zh: "他命令杰克给他画金山。" },
      { en: "But Jack painted a strong wind that blew the king away.", zh: "但杰克画了一阵强风，把国王吹走了。" },
      { en: "Jack continued to use his gift to help others.", zh: "杰克继续用他的天赋帮助别人。" }
    ]
  },
  {
    id: 10,
    title: "The Science Fair",
    level: "Intermediate",
    sentences: [
      { en: "Every year, our school holds a science fair in spring.", zh: "每年春天，我们学校都会举办科技展。" },
      { en: "Students work in groups to create science projects.", zh: "学生们分组制作科技项目。" },
      { en: "This year, my group decided to build a small volcano.", zh: "今年，我们组决定做一个小火山。" },
      { en: "We used baking soda and vinegar to make it erupt.", zh: "我们用小苏打和醋让它喷发。" },
      { en: "It took us two weeks to finish the project.", zh: "我们花了两周时间完成这个项目。" },
      { en: "On the day of the fair, we were all very excited.", zh: "科技展那天，我们都非常兴奋。" },
      { en: "Many students and parents came to see our volcano.", zh: "很多学生和家长来看我们的小火山。" },
      { en: "When it erupted, everyone clapped and cheered.", zh: "当它喷发时，所有人都鼓掌欢呼。" },
      { en: "We won the first prize for the most creative project.", zh: "我们获得了最具创意项目一等奖。" },
      { en: "Science is amazing when you explore it with friends.", zh: "和朋友一起探索科学是件奇妙的事。" }
    ]
  },
  {
    id: 11,
    title: "The Old Lighthouse",
    level: "Intermediate",
    sentences: [
      { en: "On a rocky cliff by the sea stood an old lighthouse.", zh: "海边的岩石悬崖上矗立着一座古老的灯塔。" },
      { en: "It had guided ships safely for over a hundred years.", zh: "它已经引导船只安全航行了一百多年。" },
      { en: "An old keeper named Robert lived there alone.", zh: "一位叫罗伯特的老守塔人独自住在那里。" },
      { en: "Every night, he lit the lamp and watched the sea.", zh: "每天晚上，他点亮灯火，注视着大海。" },
      { en: "One stormy night, a ship was heading toward the rocks.", zh: "一个暴风雨的夜晚，一艘船正向岩石驶去。" },
      { en: "Robert turned the lamp to its brightest setting.", zh: "罗伯特把灯调到了最亮。" },
      { en: "The ship's captain saw the light and changed course.", zh: "船长看到了灯光，改变了航向。" },
      { en: "The ship was saved, and all the sailors were safe.", zh: "船得救了，所有水手都平安无事。" },
      { en: "Robert felt proud of his important job.", zh: "罗伯特为自己重要的工作感到自豪。" },
      { en: "The old lighthouse continued to shine, night after night.", zh: "古老的灯塔夜复一夜地继续闪耀着。" }
    ]
  },
  {
    id: 12,
    title: "Learning to Ride a Bike",
    level: "Beginner",
    sentences: [
      { en: "When I was seven, my father bought me a bicycle.", zh: "我七岁时，爸爸给我买了一辆自行车。" },
      { en: "It was red and shiny, and I loved it immediately.", zh: "它又红又亮，我立刻就爱上了它。" },
      { en: "But I didn't know how to ride it yet.", zh: "但我还不会骑。" },
      { en: "On Saturday morning, my father took me to the park.", zh: "星期六早上，爸爸带我去了公园。" },
      { en: "He held the back of the seat as I pedaled.", zh: "我踩踏板时，他扶着座椅后面。" },
      { en: "Don't let go! I shouted nervously.", zh: "别放手！我紧张地喊道。" },
      { en: "I'm right here, he said with a smile.", zh: "我就在这里，他微笑着说。" },
      { en: "Slowly, I gained confidence and balanced on my own.", zh: "慢慢地，我有了信心，自己保持平衡了。" },
      { en: "I rode all the way across the park by myself!", zh: "我自己骑着穿过了整个公园！" },
      { en: "That day, I learned that practice makes perfect.", zh: "那天，我学到了熟能生巧。" }
    ]
  }
];
