# -*- coding: utf-8 -*-
"""Generate CET-4 extra words JavaScript file."""
import json

# CET-4 additional words: word|pos|meaning
# Organized A-Z, includes words NOT in the existing 288-word list
WORDS_RAW = """
acid|n./adj.|酸；酸的
acre|n.|英亩
across|prep./adv.|横过；穿过
act|n./v.|行为；行动
action|n.|行动；行为
active|adj.|积极的；活跃的
activity|n.|活动；活力
actor|n.|演员
actress|n.|女演员
actually|adv.|实际上；事实上
acute|adj.|急性的；敏锐的
adaptation|n.|适应；改编
additional|adj.|附加的；额外的
adjustment|n.|调整；调节
admission|n.|准许进入；承认
adolescent|n./adj.|青少年
adoption|n.|收养；采用
advancement|n.|前进；提升
adventurous|adj.|爱冒险的
advertising|n.|广告
advise|v.|建议；忠告
affair|n.|事务；事件
affordable|adj.|负担得起的
afraid|adj.|害怕的；担心的
after|prep./conj.|在...之后
afternoon|n.|下午
afterward|adv.|后来；以后
again|adv.|又；再
against|prep.|反对；逆
age|n./v.|年龄；变老
aggressive|adj.|侵略性的；有进取心的
ago|adv.|以前
agree|v.|同意；赞成
agreement|n.|协议；同意
aid|n./v.|援助；帮助
aircraft|n.|飞行器
airplane|n.|飞机
airport|n.|机场
algebra|n.|代数
all|adj./pron.|全部的
alliance|n.|联盟；同盟
allowance|n.|津贴；限额
almost|adv.|几乎；差不多
aluminum|n.|铝
always|adv.|总是；一直
amateur|n./adj.|业余爱好者
amaze|v.|使惊奇
ambulance|n.|救护车
among|prep.|在...之中
ample|adj.|充足的；丰富的
analogy|n.|类比；类推
analysis|n.|分析
ancestor|n.|祖先
anger|n./v.|愤怒
angry|adj.|愤怒的
animal|n.|动物
ankle|n.|脚踝
anniversary|n.|周年纪念日
anonymous|adj.|匿名的
another|adj./pron.|另一个
answer|n./v.|回答；答案
anxiety|n.|焦虑；渴望
any|adj./pron.|任何的
anybody|pron.|任何人
anyhow|adv.|无论如何
anyone|pron.|任何人
anything|pron.|任何事
anyway|adv.|无论如何
anywhere|adv.|任何地方
apartment|n.|公寓
apologize|v.|道歉
apparently|adv.|显然地
appearance|n.|外观；出现
apple|n.|苹果
application|n.|申请；应用
appointment|n.|约会；任命
approval|n.|赞成；批准
arch|n./v.|拱门
argument|n.|争论；论点
arm|n./v.|手臂；武装
army|n.|军队
around|adv./prep.|周围；大约
arrangement|n.|安排；布置
arrival|n.|到达；到来
arrow|n.|箭
art|n.|艺术
artist|n.|艺术家
as|conj./prep.|作为；当...时
ash|n.|灰烬
aside|adv.|在旁边
ask|v.|询问；要求
assemble|v.|集合；装配
assembly|n.|集会；装配
assert|v.|断言；维护
asset|n.|资产
assignment|n.|任务；分配
assistant|n./adj.|助手
association|n.|协会；关联
assumption|n.|假设
astronaut|n.|宇航员
astronomy|n.|天文学
atom|n.|原子
attack|v./n.|攻击
attentive|adj.|注意的；留心的
attorney|n.|律师
attractive|adj.|有吸引力的
attribute|v./n.|归因于；属性
auction|n./v.|拍卖
audio|adj.|音频的
August|n.|八月
aunt|n.|阿姨；姑母
author|n.|作者
automobile|n.|汽车
autumn|n.|秋天
avenue|n.|大道
awake|adj./v.|醒着的；唤醒
awful|adj.|可怕的；糟糕的
awkward|adj.|尴尬的；笨拙的
back|n./adv./v.|背面；向后；支持
background|n.|背景
backward|adv./adj.|向后
bacon|n.|培根
bacteria|n.|细菌
bad|adj.|坏的
badly|adv.|坏地；严重地
bag|n.|包；袋
baggage|n.|行李
bake|v.|烘焙
bakery|n.|面包店
balance|n./v.|平衡
balcony|n.|阳台
ball|n.|球；舞会
ballet|n.|芭蕾舞
balloon|n.|气球
bamboo|n.|竹子
banana|n.|香蕉
band|n.|乐队；带
bang|n./v.|砰的一声
bank|n.|银行；河岸
bar|n.|酒吧；条
barber|n.|理发师
bare|adj.|赤裸的；空的
bargain|n./v.|便宜货；讨价还价
bark|n./v.|树皮；吠叫
barrier|n.|障碍；屏障
baseball|n.|棒球
basin|n.|盆地；水盆
basis|n.|基础；根据
basket|n.|篮子
bat|n.|蝙蝠；球拍
bath|n.|洗澡
bathe|v.|洗澡
bathroom|n.|浴室
battle|n./v.|战斗
bay|n.|海湾
beach|n.|海滩
beam|n./v.|横梁；照射
bean|n.|豆
bear|v./n.|承受；熊
beard|n.|胡须
beast|n.|野兽
beat|v.|打败；敲打
beautiful|adj.|美丽的
beauty|n.|美丽；美人
because|conj.|因为
become|v.|变成
bed|n.|床
bedroom|n.|卧室
bee|n.|蜜蜂
beef|n.|牛肉
beer|n.|啤酒
before|prep./conj.|在...之前
beg|v.|乞求
begin|v.|开始
beginning|n.|开始
behalf|n.|代表
behave|v.|表现；行为
behavior|n.|行为；举止
behind|prep./adv.|在...后面
being|n.|存在；生物
belief|n.|信念；信仰
bell|n.|铃；钟
belong|v.|属于
below|prep./adv.|在...下面
belt|n.|腰带
bench|n.|长凳
bend|v./n.|弯曲
beneath|prep.|在...之下
beside|prep.|在...旁边
best|adj./adv.|最好的
bet|v./n.|打赌
better|adj./adv.|更好的
between|prep.|在...之间
bicycle|n.|自行车
big|adj.|大的
bike|n.|自行车
bill|n.|账单；钞票
billion|n.|十亿
bind|v.|绑；约束
biography|n.|传记
bird|n.|鸟
birth|n.|出生
birthday|n.|生日
biscuit|n.|饼干
bit|n.|一点
bite|v./n.|咬
black|adj.|黑色的
blackboard|n.|黑板
blame|v./n.|责备
blanket|n.|毯子
blast|n./v.|爆炸
blaze|n./v.|火焰；燃烧
bleed|v.|流血
blend|v./n.|混合
bless|v.|祝福
blind|adj.|盲的
block|n./v.|街区；阻塞
blood|n.|血
bloody|adj.|血腥的
bloom|n./v.|花；开花
blouse|n.|衬衫
blow|v./n.|吹；打击
blue|adj.|蓝色的
board|n./v.|木板；上船
boat|n.|船
body|n.|身体
boil|v.|煮沸
bold|adj.|大胆的
bomb|n./v.|炸弹
bond|n.|纽带；债券
bone|n.|骨头
book|n./v.|书；预订
boot|n.|靴子
border|n./v.|边界
bore|v.|使厌烦
born|adj.|出生的
borrow|v.|借
boss|n.|老板
both|pron./adj.|两者
bottle|n.|瓶子
bottom|n.|底部
bounce|v.|弹跳
bound|adj./v.|被绑的；跳跃
boundary|n.|边界
bow|n./v.|弓；鞠躬
bowl|n.|碗
box|n.|盒子
boy|n.|男孩
boyfriend|n.|男朋友
brain|n.|大脑
brake|n./v.|刹车
branch|n.|树枝；分支
brave|adj.|勇敢的
bread|n.|面包
break|v./n.|打破；休息
breakfast|n.|早餐
breast|n.|胸部
breath|n.|呼吸
breathe|v.|呼吸
breed|v./n.|繁殖；品种
brick|n.|砖
bridge|n.|桥
brief|adj.|简短的
bright|adj.|明亮的；聪明的
brilliant|adj.|杰出的
bring|v.|带来
broad|adj.|宽的；广泛的
broadcast|v./n.|广播
brother|n.|兄弟
brown|adj.|棕色的
brush|n./v.|刷子；刷
bubble|n.|气泡
bucket|n.|桶
build|v.|建造
building|n.|建筑物
bulb|n.|灯泡
bull|n.|公牛
bullet|n.|子弹
bunch|n.|束；串
burden|n.|负担
bureau|n.|局；办事处
burn|v.|燃烧
burst|v.|爆发
bury|v.|埋葬
bus|n.|公交车
bush|n.|灌木
business|n.|商业；生意
busy|adj.|忙碌的
but|conj.|但是
butcher|n.|屠夫
butter|n.|黄油
button|n.|纽扣；按钮
buy|v.|购买
cab|n.|出租车
cabbage|n.|卷心菜
cabin|n.|小屋
cable|n.|缆线；电缆
cafe|n.|咖啡馆
cage|n.|笼子
cake|n.|蛋糕
calculate|v.|计算
calendar|n.|日历
call|v./n.|呼叫；电话
calm|adj.|平静的
camera|n.|相机
camp|n./v.|营地；露营
campaign|n.|运动；战役
campus|n.|校园
can|v./n.|能；罐头
canal|n.|运河
cancel|v.|取消
cancer|n.|癌症
candidate|n.|候选人
candle|n.|蜡烛
candy|n.|糖果
cannon|n.|大炮
canoe|n.|独木舟
canteen|n.|食堂
canvas|n.|帆布
cap|n.|帽子
capable|adj.|有能力的
capacity|n.|容量；能力
capital|n.|首都；资本
captain|n.|队长；船长
capture|v./n.|捕获
car|n.|汽车
card|n.|卡片
care|n./v.|关心；照顾
career|n.|职业
careful|adj.|仔细的
careless|adj.|粗心的
carpet|n.|地毯
carriage|n.|马车；车厢
carrier|n.|运载工具
carrot|n.|胡萝卜
carry|v.|携带
cart|n.|手推车
cartoon|n.|卡通
case|n.|情况；案例
cash|n.|现金
cassette|n.|磁带
castle|n.|城堡
casual|adj.|随便的；休闲的
cat|n.|猫
catalog|n.|目录
catch|v.|抓住
category|n.|类别
cattle|n.|牛
cause|n./v.|原因；引起
caution|n.|谨慎
cave|n.|洞穴
ceiling|n.|天花板
celebrate|v.|庆祝
cell|n.|细胞；牢房
cellphone|n.|手机
cent|n.|分
centigrade|adj.|摄氏的
centimeter|n.|厘米
central|adj.|中心的
century|n.|世纪
ceremony|n.|仪式
certain|adj.|确定的
certainly|adv.|当然
certificate|n.|证书
chain|n.|链条
chair|n.|椅子
chairman|n.|主席
chalk|n.|粉笔
chance|n.|机会
change|n./v.|改变；零钱
channel|n.|频道；渠道
chapter|n.|章节
character|n.|性格；角色
characteristic|adj./n.|典型的；特征
charge|v./n.|充电；收费
charm|n./v.|魅力；迷住
chart|n.|图表
chase|v./n.|追逐
chat|n./v.|聊天
cheap|adj.|便宜的
cheat|v.|欺骗
check|v./n.|检查
cheek|n.|脸颊
cheer|v./n.|欢呼
cheerful|adj.|愉快的
cheese|n.|奶酪
chef|n.|厨师
chemical|adj./n.|化学的
chemistry|n.|化学
cheque|n.|支票
cherry|n.|樱桃
chess|n.|国际象棋
chest|n.|胸部
chew|v.|咀嚼
chicken|n.|鸡；鸡肉
chief|adj./n.|主要的
child|n.|孩子
childhood|n.|童年
chimney|n.|烟囱
chin|n.|下巴
china|n.|瓷器
chip|n.|芯片
chocolate|n.|巧克力
choice|n.|选择
choose|v.|选择
chopsticks|n.|筷子
chorus|n.|合唱
Christian|n./adj.|基督教的
Christmas|n.|圣诞节
church|n.|教堂
cigar|n.|雪茄
cigarette|n.|香烟
cinema|n.|电影院
circle|n./v.|圆圈；盘旋
circuit|n.|电路
circumstance|n.|情况
circus|n.|马戏团
citizen|n.|公民
city|n.|城市
civil|adj.|公民的
civilian|n.|平民
claim|v./n.|声称；要求
clap|v.|鼓掌
clarify|v.|澄清
clarity|n.|清晰
class|n.|班级；阶级
classic|adj./n.|经典的
classical|adj.|古典的
classmate|n.|同学
classroom|n.|教室
clay|n.|黏土
clean|adj./v.|干净的
clear|adj./v.|清楚的
clerk|n.|职员
clever|adj.|聪明的
click|v.|点击
client|n.|客户
cliff|n.|悬崖
climate|n.|气候
climb|v.|爬
clinic|n.|诊所
clock|n.|时钟
close|v./adj.|关闭；近的
cloth|n.|布
clothes|n.|衣服
clothing|n.|服装
cloud|n.|云
cloudy|adj.|多云的
club|n.|俱乐部
clue|n.|线索
coach|n./v.|教练；辅导
coal|n.|煤
coast|n.|海岸
coat|n.|外套
code|n.|代码
coffee|n.|咖啡
coin|n.|硬币
Coke|n.|可乐
cold|adj./n.|冷的；感冒
collar|n.|衣领
colleague|n.|同事
collect|v.|收集
collection|n.|收集品
college|n.|大学
colony|n.|殖民地
color|n.|颜色
colored|adj.|有颜色的
column|n.|柱；专栏
comb|n./v.|梳子；梳
combine|v.|结合
come|v.|来
comedy|n.|喜剧
comfort|n./v.|舒适
comfortable|adj.|舒适的
comic|adj./n.|滑稽的；漫画
command|v./n.|命令
comment|n./v.|评论
commerce|n.|商业
commercial|adj./n.|商业的
commission|n.|佣金
commit|v.|犯(罪)；承诺
committee|n.|委员会
common|adj.|常见的
communicate|v.|交流
communication|n.|交流
community|n.|社区
companion|n.|同伴
company|n.|公司
compare|v.|比较
comparison|n.|比较
compete|v.|竞争
competition|n.|竞争
competitor|n.|竞争者
complain|v.|抱怨
complaint|n.|抱怨
complete|adj./v.|完整的；完成
complex|adj.|复杂的
complicate|v.|使复杂
compliment|n./v.|赞美
compose|v.|组成；创作
composer|n.|作曲家
composition|n.|作文；构成
comprehension|n.|理解
comprehensive|adj.|全面的
compromise|n./v.|妥协
compute|v.|计算
computer|n.|计算机
conceal|v.|隐藏
concentrate|v.|集中
concept|n.|概念
concern|v./n.|关心
concerning|prep.|关于
conclude|v.|得出结论
conclusion|n.|结论
concrete|adj./n.|具体的
condition|n.|条件
conduct|v./n.|进行；行为
conductor|n.|指挥；导体
conference|n.|会议
confess|v.|承认
confidence|n.|信心
confident|adj.|自信的
confirm|v.|确认
conflict|n.|冲突
confront|v.|面对
confuse|v.|使困惑
confusion|n.|困惑
congratulate|v.|祝贺
congratulation|n.|祝贺
congress|n.|国会
connect|v.|连接
connection|n.|连接
conquer|v.|征服
conscious|adj.|有意识的
consequence|n.|后果
conservation|n.|保护
consider|v.|考虑
considerable|adj.|相当大的
consideration|n.|考虑
consist|v.|由...组成
constant|adj.|不断的
constitute|v.|构成
construct|v.|建造
construction|n.|建设
consult|v.|咨询
consultant|n.|顾问
consume|v.|消耗
consumer|n.|消费者
consumption|n.|消费
contact|n./v.|联系
contain|v.|包含
container|n.|容器
contemporary|adj.|当代的
content|n./adj.|内容；满足的
contest|n./v.|比赛
context|n.|上下文
continent|n.|大陆
continue|v.|继续
continuous|adj.|持续的
contract|n./v.|合同
contradict|v.|反驳
contrast|n./v.|对比
contribute|v.|贡献
contribution|n.|贡献
control|v./n.|控制
convenient|adj.|方便的
convention|n.|惯例；大会
conversation|n.|对话
convert|v.|转换
convince|v.|说服
cook|v./n.|烹饪
cooker|n.|炊具
cookie|n.|饼干
cool|adj.|凉爽的
cooperate|v.|合作
cooperation|n.|合作
copper|n.|铜
copy|n./v.|副本；复印
core|n.|核心
corn|n.|玉米
corner|n.|角落
corporation|n.|公司
correct|adj./v.|正确的
correction|n.|改正
correspond|v.|符合；通信
corridor|n.|走廊
cost|n./v.|花费
costume|n.|服装
cottage|n.|小屋
cotton|n.|棉花
couch|n.|沙发
cough|n./v.|咳嗽
could|v.|能(c过去式)
council|n.|委员会
count|v.|计数
counter|n.|柜台
country|n.|国家
countryside|n.|乡村
county|n.|县
couple|n.|一对
courage|n.|勇气
course|n.|课程
court|n.|法庭
courtyard|n.|庭院
cousin|n.|表兄妹
cover|v./n.|覆盖
cow|n.|奶牛
coward|n.|懦夫
crack|n./v.|裂缝
craft|n.|手艺
crash|v./n.|碰撞
crate|n.|板条箱
crayon|n.|蜡笔
crazy|adj.|疯狂的
cream|n.|奶油
create|v.|创造
creative|adj.|有创造力的
creature|n.|生物
credit|n.|信用
crew|n.|全体船员
crime|n.|罪行
criminal|n./adj.|罪犯
crisis|n.|危机
critic|n.|评论家
critical|adj.|批判的
criticism|n.|批评
criticize|v.|批评
crop|n.|庄稼
cross|v./n.|穿过；十字
crossing|n.|十字路口
crowd|n./v.|人群
crowded|adj.|拥挤的
crown|n.|王冠
crucial|adj.|关键的
cruel|adj.|残忍的
cry|v./n.|哭
cucumber|n.|黄瓜
cultural|adj.|文化的
culture|n.|文化
cup|n.|杯子
cupboard|n.|橱柜
cure|v./n.|治愈
curiosity|n.|好奇心
curious|adj.|好奇的
currency|n.|货币
current|adj./n.|当前的
curriculum|n.|课程
curtain|n.|窗帘
curve|n./v.|曲线
cushion|n.|垫子
custom|n.|习俗
customer|n.|顾客
customs|n.|海关
cut|v./n.|切
cute|adj.|可爱的
cycle|n./v.|循环；骑车
daily|adj./adv.|每日的
dairy|n./adj.|乳制品
damage|n./v.|损害
damp|adj.|潮湿的
dance|v./n.|跳舞
danger|n.|危险
dangerous|adj.|危险的
dare|v.|敢
dark|adj.|黑暗的
darkness|n.|黑暗
data|n.|数据
database|n.|数据库
date|n./v.|日期
daughter|n.|女儿
dawn|n.|黎明
day|n.|天
dead|adj.|死的
deadline|n.|截止日期
deaf|adj.|聋的
deal|v./n.|处理；交易
dear|adj.|亲爱的
death|n.|死亡
debate|n./v.|辩论
debt|n.|债务
decade|n.|十年
December|n.|十二月
decide|v.|决定
decision|n.|决定
deck|n.|甲板
declare|v.|宣布
decline|v./n.|下降
decorate|v.|装饰
decoration|n.|装饰
decrease|v./n.|减少
deed|n.|行为
deep|adj.|深的
deer|n.|鹿
defeat|v./n.|击败
defend|v.|保卫
defense|n.|防御
define|v.|定义
definite|adj.|明确的
definitely|adv.|肯定地
definition|n.|定义
degree|n.|程度；学位
delay|n./v.|延迟
delete|v.|删除
deliberately|adv.|故意地
delicate|adj.|精致的
delicious|adj.|美味的
delight|n./v.|快乐
deliver|v.|递送
delivery|n.|交付
demand|n./v.|需求
democracy|n.|民主
democratic|adj.|民主的
demonstrate|v.|证明；演示
dentist|n.|牙医
deny|v.|否认
depart|v.|出发
department|n.|部门
departure|n.|出发
depend|v.|依赖
deposit|n./v.|存款
depress|v.|使沮丧
depth|n.|深度
describe|v.|描述
description|n.|描述
desert|n./v.|沙漠；抛弃
deserve|v.|应得
design|n./v.|设计
designer|n.|设计师
desire|n./v.|渴望
desk|n.|书桌
desperate|adj.|绝望的
despite|prep.|尽管
dessert|n.|甜点
destination|n.|目的地
destroy|v.|破坏
destruction|n.|破坏
detail|n.|细节
detailed|adj.|详细的
detect|v.|发现
determination|n.|决心
determine|v.|决定
develop|v.|发展
development|n.|发展
device|n.|设备
devote|v.|奉献
dialog|n.|对话
diamond|n.|钻石
diary|n.|日记
dictionary|n.|字典
die|v.|死
diet|n.|饮食
differ|v.|不同
difference|n.|差异
different|adj.|不同的
difficult|adj.|困难的
difficulty|n.|困难
dig|v.|挖
digital|adj.|数字的
dignity|n.|尊严
dimension|n.|尺寸；维度
dine|v.|进餐
dining|n.|进餐
dinner|n.|晚餐
dip|v.|浸
diploma|n.|文凭
direct|adj./v.|直接的；指挥
direction|n.|方向
director|n.|导演；主任
dirt|n.|泥土
dirty|adj.|脏的
disabled|adj.|残疾的
disadvantage|n.|劣势
disagree|v.|不同意
disappear|v.|消失
disappoint|v.|使失望
disaster|n.|灾难
disc|n.|圆盘
discipline|n.|纪律
disco|n.|迪斯科
discount|n.|折扣
discover|v.|发现
discovery|n.|发现
discuss|v.|讨论
discussion|n.|讨论
disease|n.|疾病
dish|n.|盘子；菜肴
disk|n.|磁盘
dismiss|v.|解散
display|v./n.|展示
distance|n.|距离
distant|adj.|远的
distinct|adj.|明显的
distinguish|v.|区分
distribute|v.|分配
district|n.|区域
disturb|v.|打扰
dive|v./n.|潜水
divide|v.|分开
division|n.|分开
divorce|n./v.|离婚
dizzy|adj.|头晕的
do|v.|做
doctor|n.|医生
document|n.|文件
dog|n.|狗
doll|n.|洋娃娃
dollar|n.|美元
domestic|adj.|国内的；家庭的
dominant|adj.|占主导的
dominate|v.|支配
donate|v.|捐赠
donkey|n.|驴
door|n.|门
dormitory|n.|宿舍
dose|n.|剂量
dot|n.|点
double|adj./n./v.|双倍的
doubt|n./v.|怀疑
down|adv./prep.|向下
download|v.|下载
downtown|n./adv.|市中心
dozen|n.|一打
draft|n./v.|草稿
drag|v.|拖
dragon|n.|龙
drama|n.|戏剧
dramatic|adj.|戏剧性的
draw|v.|画；拉
drawer|n.|抽屉
drawing|n.|图画
dream|n./v.|梦想
dress|n./v.|裙子；穿衣
drift|v.|漂移
drill|n./v.|钻；训练
drink|v./n.|喝；饮料
drive|v.|驾驶
driver|n.|司机
drop|v./n.|掉落
drown|v.|溺死
drug|n.|药物
drum|n.|鼓
drunk|adj.|醉的
dry|adj./v.|干的
duck|n.|鸭子
due|adj.|到期的
dull|adj.|乏味的
dumpling|n.|饺子
during|prep.|在...期间
dust|n.|灰尘
duty|n.|责任
DVD|n.|光盘
dynamic|adj.|动态的
each|pron./adj.|每个
eager|adj.|渴望的
eagle|n.|鹰
ear|n.|耳朵
early|adj./adv.|早的
earn|v.|赚得
earth|n.|地球
earthquake|n.|地震
ease|n./v.|轻松
east|n./adj.|东方
eastern|adj.|东方的
easy|adj.|容易的
eat|v.|吃
echo|n./v.|回声
economic|adj.|经济的
economy|n.|经济
edge|n.|边缘
edit|v.|编辑
edition|n.|版本
editor|n.|编辑
educate|v.|教育
education|n.|教育
effect|n.|效果
effective|adj.|有效的
efficient|adj.|高效的
effort|n.|努力
egg|n.|鸡蛋
eight|num.|八
eighteen|num.|十八
eighty|num.|八十
either|pron./adj.|两者之一
elder|adj./n.|年长的
elderly|adj.|年长的
elect|v.|选举
election|n.|选举
electric|adj.|电的
electrical|adj.|电的
electricity|n.|电
electronic|adj.|电子的
elegant|adj.|优雅的
element|n.|元素
elephant|n.|大象
elevator|n.|电梯
eleven|num.|十一
eliminate|v.|消除
else|adv.|其他
embassy|n.|大使馆
embrace|v.|拥抱
emerge|v.|出现
emergency|n.|紧急情况
emotion|n.|情感
emotional|adj.|情感的
emperor|n.|皇帝
emphasis|n.|强调
emphasize|v.|强调
empire|n.|帝国
employ|v.|雇用
employee|n.|雇员
employer|n.|雇主
employment|n.|就业
empty|adj./v.|空的
enable|v.|使能够
enclose|v.|围住
encounter|v./n.|遭遇
encourage|v.|鼓励
encouragement|n.|鼓励
end|n./v.|结束
ending|n.|结局
endless|adj.|无尽的
endure|v.|忍受
enemy|n.|敌人
energetic|adj.|精力充沛的
energy|n.|能量
engage|v.|参与；订婚
engine|n.|引擎
engineer|n.|工程师
England|n.|英格兰
English|n./adj.|英语
enjoy|v.|享受
enjoyable|adj.|令人愉快的
enjoyment|n.|享受
enlarge|v.|扩大
enormous|adj.|巨大的
enough|adj./adv.|足够的
enrich|v.|丰富
ensure|v.|确保
enter|v.|进入
enterprise|n.|企业
entertain|v.|娱乐
entertainment|n.|娱乐
enthusiasm|n.|热情
enthusiastic|adj.|热情的
entire|adj.|整个的
entirely|adv.|完全地
entrance|n.|入口
entry|n.|进入
envelope|n.|信封
environment|n.|环境
environmental|adj.|环境的
envy|v./n.|嫉妒
equal|adj./v.|相等的
equality|n.|平等
equipment|n.|设备
era|n.|时代
error|n.|错误
escape|v./n.|逃跑
especially|adv.|特别地
essay|n.|文章
essential|adj.|必要的
establish|v.|建立
estate|n.|地产
estimate|v./n.|估计
Europe|n.|欧洲
European|adj./n.|欧洲的
eve|n.|前夜
even|adv./adj.|甚至；平的
evening|n.|晚上
event|n.|事件
eventually|adv.|最终
ever|adv.|曾经
every|adj.|每个
everybody|pron.|每个人
everyday|adj.|日常的
everyone|pron.|每个人
everything|pron.|一切
everywhere|adv.|到处
evidence|n.|证据
evident|adj.|明显的
evil|adj./n.|邪恶的
evolution|n.|进化
evolve|v.|进化
exact|adj.|确切的
exactly|adv.|确切地
exaggerate|v.|夸大
exam|n.|考试
examination|n.|考试
examine|v.|检查
example|n.|例子
excellent|adj.|优秀的
except|prep.|除了
exception|n.|例外
exchange|v./n.|交换
excite|v.|使兴奋
excited|adj.|兴奋的
exciting|adj.|令人兴奋的
exclude|v.|排除
excuse|n./v.|借口；原谅
execute|v.|执行
exercise|n./v.|锻炼
exhaust|v./n.|耗尽；排气
exhibit|v./n.|展览
exhibition|n.|展览
exist|v.|存在
existence|n.|存在
exit|n./v.|出口
expand|v.|扩展
expansion|n.|扩张
expect|v.|期望
expectation|n.|期望
expense|n.|花费
expensive|adj.|昂贵的
experience|n./v.|经验；经历
experiment|n./v.|实验
expert|n./adj.|专家
explain|v.|解释
explanation|n.|解释
explode|v.|爆炸
exploit|v.|开发；剥削
explore|v.|探索
explorer|n.|探险家
explosion|n.|爆炸
export|v./n.|出口
expose|v.|暴露
express|v./adj.|表达
expression|n.|表达
extend|v.|延伸
extension|n.|延伸
extensive|adj.|广泛的
extent|n.|程度
extra|adj.|额外的
extraordinary|adj.|非凡的
extreme|adj.|极端的
extremely|adv.|极其
eye|n.|眼睛
eyesight|n.|视力
fabric|n.|织物
face|n./v.|脸；面对
facility|n.|设施
fact|n.|事实
factor|n.|因素
factory|n.|工厂
fade|v.|褪色
fail|v.|失败
failure|n.|失败
faint|adj./v.|微弱的；昏厥
fair|adj.|公平的
fairly|adv.|相当地
fairy|n.|仙女
faith|n.|信仰
faithful|adj.|忠诚的
fake|adj./n.|假的
fall|v./n.|落下；秋天
false|adj.|错误的
fame|n.|名声
familiar|adj.|熟悉的
family|n.|家庭
famous|adj.|著名的
fan|n.|扇子；粉丝
fancy|adj./v.|花哨的；想要
fantastic|adj.|极好的
fantasy|n.|幻想
far|adj./adv.|远的
fare|n.|车费
farm|n.|农场
farmer|n.|农民
fashion|n.|时尚
fashionable|adj.|时尚的
fast|adj./adv.|快的
fasten|v.|系紧
fat|adj./n.|胖的；脂肪
fate|n.|命运
father|n.|父亲
fault|n.|错误
favor|n./v.|好意；赞成
favorable|adj.|有利的
favorite|adj./n.|最喜欢的
fear|n./v.|恐惧
feast|n.|盛宴
feather|n.|羽毛
feature|n.|特征
February|n.|二月
federal|adj.|联邦的
fee|n.|费用
feed|v.|喂养
feedback|n.|反馈
feel|v.|感觉
feeling|n.|感觉
fellow|n.|家伙
female|adj./n.|女性的
fence|n.|栅栏
festival|n.|节日
fetch|v.|取来
fever|n.|发烧
few|adj./pron.|少数的
field|n.|田野；领域
fierce|adj.|凶猛的
fifteen|num.|十五
fifty|num.|五十
fight|v./n.|战斗
figure|n./v.|数字；身材
file|n./v.|文件
fill|v.|填充
film|n.|电影
final|adj./n.|最终的
finance|n.|财政
financial|adj.|金融的
find|v.|找到
finding|n.|发现
fine|adj./n.|好的；罚款
finger|n.|手指
finish|v./n.|完成
fire|n./v.|火；开火
fireman|n.|消防员
firm|adj./n.|坚固的；公司
first|adj./adv.|第一的
fish|n./v.|鱼
fisherman|n.|渔夫
fit|adj./v.|合适的
fitness|n.|健康
five|num.|五
fix|v.|修理
flag|n.|旗帜
flame|n.|火焰
flash|v./n.|闪光
flashlight|n.|手电筒
flat|adj./n.|平的；公寓
flavor|n.|味道
flee|v.|逃跑
fleet|n.|舰队
flesh|n.|肉
flexible|adj.|灵活的
flight|n.|飞行
float|v.|漂浮
flood|n./v.|洪水
floor|n.|地板
flour|n.|面粉
flow|v./n.|流动
flower|n.|花
flu|n.|流感
fluid|n./adj.|流体
flush|v.|冲洗
flute|n.|长笛
fly|v./n.|飞
focus|v./n.|集中
fog|n.|雾
fold|v.|折叠
folk|n./adj.|民间
follow|v.|跟随
following|adj.|接下来的
fond|adj.|喜爱的
food|n.|食物
fool|n./v.|傻瓜
foolish|adj.|愚蠢的
foot|n.|脚
football|n.|足球
for|prep.|为了
forbid|v.|禁止
force|n./v.|力量；强迫
forecast|v./n.|预报
forehead|n.|前额
foreign|adj.|外国的
foreigner|n.|外国人
foresee|v.|预见
forest|n.|森林
forever|adv.|永远
forget|v.|忘记
forgive|v.|原谅
fork|n.|叉子
form|n./v.|形式
formal|adj.|正式的
former|adj./n.|前者的
formula|n.|公式
fort|n.|堡垒
forth|adv.|向前
fortnight|n.|两周
fortunate|adj.|幸运的
fortune|n.|财富；命运
forty|num.|四十
forward|adv./adj.|向前
fossil|n.|化石
found|v.|建立
foundation|n.|基础
fountain|n.|喷泉
four|num.|四
fourteen|num.|十四
fox|n.|狐狸
fragile|adj.|易碎的
frame|n./v.|框架
France|n.|法国
free|adj./v.|自由的；免费
freedom|n.|自由
freeze|v.|冻结
French|adj./n.|法国的
frequent|adj.|频繁的
frequently|adv.|频繁地
fresh|adj.|新鲜的
Friday|n.|星期五
fridge|n.|冰箱
friend|n.|朋友
friendly|adj.|友好的
friendship|n.|友谊
frighten|v.|使害怕
from|prep.|从
front|n./adj.|前面
frost|n.|霜
frown|v./n.|皱眉
fruit|n.|水果
fry|v.|油炸
fuel|n.|燃料
fulfill|v.|履行
full|adj.|满的
fun|n.|乐趣
function|n./v.|功能
fund|n.|基金
fundamental|adj.|基本的
funeral|n.|葬礼
funny|adj.|有趣的
fur|n.|毛皮
furniture|n.|家具
further|adj./adv.|更远的
furthermore|adv.|此外
fuss|n./v.|大惊小怪
future|n./adj.|未来
gain|v./n.|获得
gallery|n.|画廊
game|n.|游戏
gang|n.|帮派
gap|n.|间隙
garage|n.|车库
garbage|n.|垃圾
garden|n.|花园
garlic|n.|大蒜
gas|n.|气体
gasoline|n.|汽油
gate|n.|大门
gather|v.|聚集
gay|adj.|同性恋的
gaze|v./n.|凝视
gear|n.|齿轮
gender|n.|性别
gene|n.|基因
general|adj./n.|一般的
generally|adv.|通常
generate|v.|产生
generation|n.|一代
generous|adj.|慷慨的
genius|n.|天才
gentle|adj.|温柔的
gentleman|n.|绅士
genuine|adj.|真正的
geography|n.|地理
German|adj./n.|德国的
Germany|n.|德国
gesture|n.|手势
get|v.|得到
ghost|n.|鬼
giant|adj./n.|巨大的
gift|n.|礼物
gifted|adj.|有天赋的
giraffe|n.|长颈鹿
girl|n.|女孩
girlfriend|n.|女朋友
give|v.|给
glad|adj.|高兴的
glance|v./n.|瞥
glare|v./n.|瞪眼
glass|n.|玻璃
glasses|n.|眼镜
global|adj.|全球的
globe|n.|地球
glory|n.|荣耀
glove|n.|手套
glue|n.|胶水
go|v.|去
goal|n.|目标
goat|n.|山羊
god|n.|神
gold|n./adj.|金
golden|adj.|金色的
golf|n.|高尔夫
good|adj.|好的
goodbye|n.|再见
goods|n.|货物
goose|n.|鹅
govern|v.|统治
government|n.|政府
grade|n./v.|等级
gradual|adj.|逐渐的
gradually|adv.|逐渐地
graduate|v./n.|毕业
grain|n.|谷物
gram|n.|克
grammar|n.|语法
grand|adj.|宏伟的
grandchild|n.|孙辈
grandfather|n.|祖父
grandmother|n.|祖母
grandparent|n.|祖父母
grant|v./n.|授予
grape|n.|葡萄
graph|n.|图表
grasp|v./n.|抓住
grass|n.|草
grateful|adj.|感激的
gravity|n.|重力
gray|adj.|灰色的
great|adj.|伟大的
greedy|adj.|贪婪的
Greek|adj./n.|希腊的
green|adj.|绿色的
greet|v.|问候
greeting|n.|问候
grill|n./v.|烤架
grocery|n.|杂货
gross|adj.|总的
ground|n.|地面
group|n./v.|组
grow|v.|生长
growth|n.|增长
guarantee|v./n.|保证
guard|n./v.|守卫
guess|v./n.|猜测
guest|n.|客人
guidance|n.|指导
guide|n./v.|向导
guilty|adj.|有罪的
guitar|n.|吉他
gulf|n.|海湾
gum|n.|口香糖
gun|n.|枪
guy|n.|家伙
gym|n.|健身房
habit|n.|习惯
hair|n.|头发
haircut|n.|理发
half|n./adj./adv.|一半
hall|n.|大厅
ham|n.|火腿
hamburger|n.|汉堡包
hammer|n.|锤子
hand|n./v.|手
handbag|n.|手提包
handful|n.|一把
handicap|n.|障碍
handkerchief|n.|手帕
handle|n./v.|把手；处理
handsome|adj.|英俊的
handwriting|n.|笔迹
handy|adj.|方便的
hang|v.|悬挂
happen|v.|发生
happiness|n.|幸福
happy|adj.|快乐的
harbor|n.|港口
hard|adj./adv.|硬的；努力地
hardly|adv.|几乎不
hardship|n.|困难
hardware|n.|硬件
harm|n./v.|伤害
harmful|adj.|有害的
harmony|n.|和谐
harvest|n./v.|收获
hat|n.|帽子
hate|v./n.|讨厌
have|v.|有
he|pron.|他
head|n./v.|头
headache|n.|头痛
headline|n.|标题
headmaster|n.|校长
headquarters|n.|总部
health|n.|健康
healthy|adj.|健康的
heap|n.|堆
hear|v.|听见
hearing|n.|听力
heart|n.|心
heat|n./v.|热
heating|n.|供暖
heaven|n.|天堂
heavy|adj.|重的
height|n.|高度
helicopter|n.|直升机
hell|n.|地狱
hello|n./int.|你好
help|v./n.|帮助
helpful|adj.|有帮助的
hen|n.|母鸡
her|pron.|她的
here|adv.|这里
hero|n.|英雄
hesitate|v.|犹豫
hide|v.|藏
high|adj./adv.|高的
highlight|v./n.|强调
highway|n.|高速公路
hike|v./n.|徒步
hill|n.|小山
him|pron.|他
himself|pron.|他自己
hire|v.|雇佣
his|pron.|他的
historic|adj.|历史性的
historical|adj.|历史的
history|n.|历史
hit|v./n.|打
hobby|n.|爱好
hold|v./n.|拿
hole|n.|洞
holiday|n.|假日
hollow|adj.|空心的
holy|adj.|神圣的
home|n./adv.|家
homeland|n.|祖国
homesick|adj.|想家的
hometown|n.|故乡
homework|n.|作业
honest|adj.|诚实的
honey|n.|蜂蜜
honor|n./v.|荣誉
hook|n./v.|钩子
hope|n./v.|希望
hopeful|adj.|有希望的
hopefully|adv.|有希望地
horizon|n.|地平线
horn|n.|角
horrible|adj.|可怕的
horror|n.|恐怖
horse|n.|马
hospital|n.|医院
host|n./v.|主人
hostess|n.|女主人
hot|adj.|热的
hotel|n.|酒店
hour|n.|小时
house|n.|房子
household|n.|家庭
housework|n.|家务
housing|n.|住房
how|adv.|怎样
however|adv./conj.|然而
hug|v./n.|拥抱
huge|adj.|巨大的
human|adj./n.|人类的
humble|adj.|谦虚的
humor|n.|幽默
humorous|adj.|幽默的
hundred|num.|百
hunger|n.|饥饿
hungry|adj.|饥饿的
hunt|v.|打猎
hunter|n.|猎人
hurry|n./v.|匆忙
hurt|v.|伤害
husband|n.|丈夫
hut|n.|小屋
hydrogen|n.|氢
I|pron.|我
ice|n.|冰
ice cream|n.|冰淇淋
idea|n.|想法
ideal|adj./n.|理想的
identify|v.|识别
identity|n.|身份
idiom|n.|习语
if|conj.|如果
ignorant|adj.|无知的
ignore|v.|忽视
ill|adj.|病的
illegal|adj.|非法的
illness|n.|疾病
illustrate|v.|说明
image|n.|图像
imagination|n.|想象力
imagine|v.|想象
immediate|adj.|立即的
immediately|adv.|立即
immigrant|n.|移民
impact|n./v.|影响
imply|v.|暗示
import|v./n.|进口
importance|n.|重要性
important|adj.|重要的
impossible|adj.|不可能的
impress|v.|给...印象
impression|n.|印象
impressive|adj.|令人印象深刻的
improve|v.|改善
improvement|n.|改善
in|prep.|在...里
inch|n.|英寸
incident|n.|事件
include|v.|包括
including|prep.|包括
income|n.|收入
increase|v./n.|增加
incredible|adj.|难以置信的
indeed|adv.|确实
independent|adj.|独立的
index|n.|索引
indicate|v.|表明
indication|n.|指示
individual|adj./n.|个人的
indoor|adj.|室内的
industrial|adj.|工业的
industry|n.|工业
inevitable|adj.|不可避免的
infect|v.|感染
inflation|n.|通货膨胀
influence|n./v.|影响
inform|v.|通知
informal|adj.|非正式的
information|n.|信息
ingredient|n.|原料
initial|adj.|最初的
initiative|n.|倡议
injury|n.|伤害
ink|n.|墨水
inn|n.|客栈
inner|adj.|内部的
innocent|adj.|无辜的
inquire|v.|询问
inquiry|n.|询问
insect|n.|昆虫
inside|prep./adv.|在...内
insist|v.|坚持
inspect|v.|检查
inspire|v.|激励
install|v.|安装
instance|n.|例子
instant|adj./n.|立即的
instead|adv.|代替
instinct|n.|本能
institute|n.|机构
institution|n.|机构
instruct|v.|指示
instruction|n.|指示
instrument|n.|工具
insurance|n.|保险
intellectual|adj./n.|智力的
intelligence|n.|智力
intelligent|adj.|聪明的
intend|v.|打算
intense|adj.|强烈的
intention|n.|意图
interact|v.|互动
interaction|n.|互动
interest|n./v.|兴趣
interesting|adj.|有趣的
interfere|v.|干涉
interior|n./adj.|内部的
intermediate|adj.|中级的
international|adj.|国际的
internet|n.|互联网
interpret|v.|解释
interpreter|n.|翻译员
interrupt|v.|打断
interval|n.|间隔
interview|n./v.|面试
into|prep.|进入
introduce|v.|介绍
introduction|n.|介绍
invent|v.|发明
invention|n.|发明
inventor|n.|发明者
invest|v.|投资
investigate|v.|调查
investigation|n.|调查
invitation|n.|邀请
invite|v.|邀请
involve|v.|涉及
iron|n./v.|铁；熨
island|n.|岛
issue|n./v.|问题
it|pron.|它
Italian|adj./n.|意大利的
item|n.|项目
its|pron.|它的
itself|pron.|它自己
jacket|n.|夹克
jail|n.|监狱
jam|n.|果酱
January|n.|一月
Japan|n.|日本
Japanese|adj./n.|日本的
jazz|n.|爵士乐
jealous|adj.|嫉妒的
jeans|n.|牛仔裤
jeep|n.|吉普车
jet|n.|喷气式飞机
jewel|n.|宝石
jewelry|n.|珠宝
job|n.|工作
jog|v.|慢跑
join|v.|加入
joint|adj./n.|联合的
joke|n./v.|笑话
journal|n.|日记
journalist|n.|记者
journey|n.|旅程
joy|n.|快乐
judge|n./v.|法官；判断
judgment|n.|判断
juice|n.|果汁
July|n.|七月
jump|v./n.|跳
June|n.|六月
jungle|n.|丛林
junior|adj./n.|年少的
just|adv./adj.|刚刚；公正的
justice|n.|正义
justify|v.|证明...正当
keen|adj.|热心的
keep|v.|保持
ketchup|n.|番茄酱
kettle|n.|水壶
key|n./adj.|钥匙；关键的
keyboard|n.|键盘
kick|v./n.|踢
kid|n.|小孩
kill|v.|杀死
kilo|n.|千克
kilogram|n.|千克
kilometer|n.|千米
kind|n./adj.|种类；善良的
kindergarten|n.|幼儿园
kindness|n.|善良
king|n.|国王
kingdom|n.|王国
kiss|v./n.|吻
kitchen|n.|厨房
kite|n.|风筝
knee|n.|膝盖
knife|n.|刀
knock|v./n.|敲
know|v.|知道
knowledge|n.|知识
known|adj.|已知的
lab|n.|实验室
label|n./v.|标签
labor|n.|劳动
laboratory|n.|实验室
lack|n./v.|缺乏
ladder|n.|梯子
lady|n.|女士
lake|n.|湖
lamb|n.|羊羔
lamp|n.|灯
land|n./v.|土地
landlord|n.|房东
landscape|n.|风景
language|n.|语言
lantern|n.|灯笼
lap|n.|大腿
large|adj.|大的
largely|adv.|主要地
laser|n.|激光
last|adj./adv./v.|最后的；持续
late|adj./adv.|迟的
lately|adv.|最近
later|adv.|后来
latest|adj.|最新的
latter|adj./n.|后者的
laugh|v./n.|笑
laughter|n.|笑声
launch|v./n.|发射
laundry|n.|洗衣店
lavatory|n.|洗手间
law|n.|法律
lawn|n.|草坪
lawyer|n.|律师
lay|v.|放置
layer|n.|层
lazy|adj.|懒惰的
lead|v./n.|引导；铅
leader|n.|领导者
leadership|n.|领导力
leaf|n.|叶子
league|n.|联盟
leak|v./n.|泄漏
lean|v.|倾斜
learn|v.|学习
learning|n.|学习
least|adj./adv.|最少的
leather|n.|皮革
leave|v./n.|离开
lecture|n./v.|讲座
left|adj./n.|左边的
leg|n.|腿
legal|adj.|合法的
lemon|n.|柠檬
lemonade|n.|柠檬水
lend|v.|借出
length|n.|长度
less|adj./adv.|更少的
lesson|n.|课程
let|v.|让
letter|n.|信
level|n.|水平
liberal|adj.|自由的
library|n.|图书馆
license|n.|执照
lick|v.|舔
lid|n.|盖子
lie|v./n.|躺；谎言
life|n.|生活
lifestyle|n.|生活方式
lifetime|n.|一生
lift|v./n.|举起
light|n./adj.|光；轻的
lightning|n.|闪电
like|v./prep.|喜欢；像
likely|adj./adv.|可能的
limit|n./v.|限制
limited|adj.|有限的
line|n./v.|线
link|n./v.|链接
lion|n.|狮子
lip|n.|嘴唇
liquid|n./adj.|液体
list|n./v.|列表
listen|v.|听
literary|adj.|文学的
literature|n.|文学
liter|n.|升
litter|n./v.|垃圾
little|adj./adv.|小的
live|v./adj.|生活；活的
lively|adj.|活泼的
living|adj./n.|活着的
load|n./v.|负荷
loaf|n.|一条面包
loan|n./v.|贷款
local|adj.|当地的
locate|v.|位于
location|n.|位置
lock|n./v.|锁
log|n./v.|原木
logic|n.|逻辑
logical|adj.|合逻辑的
lonely|adj.|孤独的
long|adj./adv./v.|长的；渴望
look|v./n.|看
loose|adj.|松的
lord|n.|主
lorry|n.|卡车
lose|v.|丢失
loss|n.|损失
lost|adj.|丢失的
lot|n.|很多
loud|adj.|大声的
loudly|adv.|大声地
loudspeaker|n.|喇叭
love|n./v.|爱
lovely|adj.|可爱的
low|adj./adv.|低的
loyal|adj.|忠诚的
luck|n.|运气
lucky|adj.|幸运的
luggage|n.|行李
lunch|n.|午餐
lung|n.|肺
luxury|n.|奢侈
machine|n.|机器
mad|adj.|疯狂的
magazine|n.|杂志
magic|n./adj.|魔法
magician|n.|魔术师
mail|n./v.|邮件
mailbox|n.|信箱
main|adj.|主要的
mainly|adv.|主要地
maintain|v.|维持
major|adj./n./v.|主要的；专业
majority|n.|多数
make|v.|制作
male|adj./n.|男性的
man|n.|男人
manage|v.|管理
management|n.|管理
manager|n.|经理
mankind|n.|人类
manner|n.|方式；礼貌
manual|adj./n.|手动的
manufacture|v.|制造
manuscript|n.|手稿
many|adj./pron.|许多
map|n.|地图
March|n.|三月
margin|n.|边缘
mark|n./v.|标记
market|n.|市场
marriage|n.|婚姻
married|adj.|已婚的
marry|v.|结婚
marvelous|adj.|了不起的
mask|n./v.|面具
mass|n.|大量
massive|adj.|大量的
master|n./v.|主人；掌握
mat|n.|垫子
match|n./v.|比赛
mate|n.|伙伴
material|n.|材料
mathematics|n.|数学
matter|n./v.|事情
mature|adj.|成熟的
maximum|adj./n.|最大的
may|v./n.|可以；五月
maybe|adv.|也许
mayor|n.|市长
me|pron.|我
meal|n.|一餐
mean|v./adj.|意思是；吝啬的
meaning|n.|意思
meaningful|adj.|有意义的
means|n.|手段
meantime|n.|同时
meanwhile|adv.|同时
measure|n./v.|测量
measurement|n.|测量
meat|n.|肉
mechanic|n.|机械师
medical|adj.|医疗的
medicine|n.|药物
medium|adj./n.|中等的
meet|v.|遇见
meeting|n.|会议
melon|n.|瓜
melt|v.|融化
member|n.|成员
membership|n.|会员资格
memorial|n./adj.|纪念碑
memory|n.|记忆
mend|v.|修补
mental|adj.|精神的
mention|v./n.|提到
menu|n.|菜单
merchant|n.|商人
mercy|n.|仁慈
mere|adj.|仅仅
merely|adv.|仅仅
merry|adj.|快乐的
mess|n./v.|混乱
message|n.|消息
messy|adj.|凌乱的
metal|n.|金属
method|n.|方法
meter|n.|米
microphone|n.|麦克风
microscope|n.|显微镜
middle|n./adj.|中间的
midnight|n.|午夜
might|v.|可能
mild|adj.|温和的
mile|n.|英里
military|adj.|军事的
milk|n.|牛奶
million|num.|百万
mind|n./v.|头脑；介意
mine|pron./n.|我的；矿
mineral|n.|矿物
minister|n.|部长
ministry|n.|部
minor|adj./n.|次要的
minority|n.|少数
minute|n.|分钟
miracle|n.|奇迹
mirror|n.|镜子
miss|v.|想念
missing|adj.|失踪的
mission|n.|使命
mistake|n./v.|错误
mistaken|adj.|错误的
mister|n.|先生
misunderstand|v.|误解
mix|v.|混合
mixture|n.|混合物
mobile|adj.|移动的
model|n.|模型
modern|adj.|现代的
modest|adj.|谦虚的
mom|n.|妈妈
moment|n.|时刻
Monday|n.|星期一
money|n.|钱
monitor|n./v.|显示器；监控
monkey|n.|猴子
month|n.|月
monthly|adj./adv.|每月的
monument|n.|纪念碑
mood|n.|心情
moon|n.|月亮
moral|adj./n.|道德的
more|adj./adv.|更多的
moreover|adv.|此外
morning|n.|早晨
most|adj./adv.|最多的
mostly|adv.|主要地
mother|n.|母亲
motion|n.|运动
motivate|v.|激励
motor|n.|马达
mount|v./n.| mounting
mountain|n.|山
mouse|n.|老鼠
mouth|n.|嘴
move|v.|移动
movement|n.|运动
movie|n.|电影
much|adj./adv.|多的
mud|n.|泥
multiple|adj.|多个的
murder|n./v.|谋杀
muscle|n.|肌肉
museum|n.|博物馆
music|n.|音乐
musical|adj.|音乐的
musician|n.|音乐家
must|v.|必须
my|pron.|我的
myself|pron.|我自己
mysterious|adj.|神秘的
mystery|n.|神秘
nail|n.|钉子
name|n./v.|名字
narrow|adj.|窄的
nation|n.|国家
national|adj.|国家的
nationality|n.|国籍
native|adj./n.|本地的
natural|adj.|自然的
naturally|adv.|自然地
nature|n.|自然
naughty|adj.|淘气的
navy|n.|海军
near|prep./adj./adv.|近的
nearby|adj./adv.|附近的
nearly|adv.|几乎
neat|adj.|整洁的
necessary|adj.|必要的
necessity|n.|必要性
neck|n.|脖子
need|v./n.|需要
needle|n.|针
negative|adj.|消极的
neglect|v./n.|忽视
negotiate|v.|谈判
neighbor|n.|邻居
neighborhood|n.|社区
neither|pron./adj./conj.|两者都不
nephew|n.|侄子
nerve|n.|神经
nervous|adj.|紧张的
net|n.|网
network|n.|网络
never|adv.|从不
nevertheless|adv.|然而
new|adj.|新的
news|n.|新闻
newspaper|n.|报纸
next|adj./adv.|下一个
nice|adj.|好的
niece|n.|侄女
night|n.|夜晚
nine|num.|九
nineteen|num.|十九
ninety|num.|九十
no|adv./adj.|不
nobody|pron.|没有人
nod|v./n.|点头
noise|n.|噪音
noisy|adj.|吵闹的
none|pron.|没有人
nonsense|n.|废话
noodle|n.|面条
noon|n.|中午
nor|conj.|也不
normal|adj.|正常的
normally|adv.|通常
north|n./adj.|北
northern|adj.|北方的
nose|n.|鼻子
not|adv.|不
note|n./v.|笔记
notebook|n.|笔记本
nothing|pron.|没有什么
notice|n./v.|注意
novel|n./adj.|小说
November|n.|十一月
now|adv.|现在
nowadays|adv.|如今
nowhere|adv.|任何地方都不
nuclear|adj.|核的
number|n.|数字
numerous|adj.|许多的
nurse|n.|护士
nut|n.|坚果
obey|v.|服从
object|n./v.|物体；反对
objective|n./adj.|目标
observation|n.|观察
observe|v.|观察
obstacle|n.|障碍
obtain|v.|获得
obvious|adj.|明显的
obviously|adv.|明显地
occasion|n.|场合
occupation|n.|职业
occupy|v.|占据
occur|v.|发生
ocean|n.|海洋
o'clock|adv.|...点钟
October|n.|十月
odd|adj.|奇怪的
of|prep.|...的
off|adv./prep.|离开
offer|v./n.|提供
office|n.|办公室
officer|n.|官员
official|adj./n.|官方的
often|adv.|经常
oh|int.|哦
oil|n.|油
OK|adj./adv.|好的
old|adj.|老的
Olympic|adj.|奥运的
omit|v.|省略
on|prep./adv.|在...上
once|adv./conj.|一次
one|num./pron.|一
oneself|pron.|自己
onion|n.|洋葱
online|adj./adv.|在线的
only|adj./adv.|只有
onto|prep.|到...上
open|adj./v.|打开
opening|n.|开口
opera|n.|歌剧
operate|v.|操作
operation|n.|操作
operator|n.|操作员
opinion|n.|观点
opportunity|n.|机会
oppose|v.|反对
opposite|adj./n.|对面的
optimistic|adj.|乐观的
option|n.|选择
optional|adj.|可选的
or|conj.|或者
oral|adj.|口头的
orange|n./adj.|橙子
orchestra|n.|管弦乐队
order|n./v.|顺序；命令
ordinary|adj.|普通的
organization|n.|组织
organize|v.|组织
origin|n.|起源
original|adj.|原来的
ostrich|n.|鸵鸟
other|adj./pron.|其他的
otherwise|adv.|否则
ought|v.|应该
our|pron.|我们的
ours|pron.|我们的
ourselves|pron.|我们自己
out|adv./prep.|外面
outcome|n.|结果
outdoor|adj.|户外的
outer|adj.|外部的
outline|n./v.|概述
output|n.|产出
outside|n./adv./prep.|外面
outstanding|adj.|杰出的
oven|n.|烤箱
over|prep./adv.|在...上方
overcoat|n.|大衣
overcome|v.|克服
overlook|v.|忽视
overseas|adv./adj.|海外的
overweight|adj.|超重的
owe|v.|欠
own|adj./v.|自己的
owner|n.|主人
ownership|n.|所有权
ox|n.|牛
oxygen|n.|氧气
pace|n./v.|步伐
pack|v./n.|打包
package|n.|包裹
page|n.|页
pain|n.|疼痛
paint|v./n.|画
painter|n.|画家
painting|n.|画作
pair|n.|一对
palace|n.|宫殿
pale|adj.|苍白的
pan|n.|平底锅
pancake|n.|煎饼
panda|n.|熊猫
panic|n./v.|恐慌
pants|n.|裤子
paper|n.|纸
paragraph|n.|段落
parcel|n.|包裹
pardon|n./v.|原谅
parent|n.|父母
park|n./v.|公园
parking|n.|停车
parliament|n.|议会
part|n./v.|部分
participate|v.|参与
particular|adj.|特定的
particularly|adv.|特别地
partly|adv.|部分地
partner|n.|伙伴
party|n.|聚会；党派
pass|v.|通过
passage|n.|通道
passenger|n.|乘客
passion|n.|热情
passionate|adj.|热情的
passive|adj.|被动的
passport|n.|护照
password|n.|密码
past|adj./n./prep.|过去的
path|n.|小路
patience|n.|耐心
patient|adj./n.|耐心的；病人
pattern|n.|模式
pause|n./v.|暂停
pavement|n.|人行道
paw|n.|爪子
pay|v./n.|支付
payment|n.|支付
pea|n.|豌豆
peace|n.|和平
peaceful|adj.|和平的
peach|n.|桃子
peak|n.|山峰
peanut|n.|花生
pear|n.|梨
pearl|n.|珍珠
peasant|n.|农民
pen|n.|钢笔
pencil|n.|铅笔
penguin|n.|企鹅
penny|n.|便士
people|n.|人们
pepper|n.|胡椒
percent|n.|百分比
perfect|adj.|完美的
perform|v.|表演
performance|n.|表现
perhaps|adv.|也许
period|n.|时期
permanent|adj.|永久的
permission|n.|许可
permit|v./n.|允许
persist|v.|坚持
person|n.|人
personal|adj.|个人的
personality|n.|个性
perspective|n.|视角
pet|n.|宠物
petrol|n.|汽油
phenomenon|n.|现象
philosophy|n.|哲学
phone|n./v.|电话
photo|n.|照片
photograph|n.|照片
photographer|n.|摄影师
phrase|n.|短语
physical|adj.|身体的
physician|n.|医生
physics|n.|物理学
piano|n.|钢琴
pick|v.|捡
picnic|n.|野餐
picture|n.|图片
pie|n.|馅饼
piece|n.|块
pig|n.|猪
pigeon|n.|鸽子
pile|n./v.|堆
pill|n.|药丸
pillow|n.|枕头
pilot|n.|飞行员
pin|n./v.|针
pine|n.|松树
pineapple|n.|菠萝
ping-pong|n.|乒乓球
pink|adj.|粉色的
pioneer|n.|先驱
pipe|n.|管子
pirate|n.|海盗
pity|n./v.|遗憾
pizza|n.|披萨
place|n./v.|地方
plain|adj./n.|朴素的
plan|n./v.|计划
plane|n.|飞机
planet|n.|行星
plant|n./v.|植物
plastic|n./adj.|塑料
plate|n.|盘子
platform|n.|平台
play|v./n.|玩
player|n.|选手
playground|n.|操场
pleasant|adj.|令人愉快的
please|v.|请
pleased|adj.|高兴的
pleasure|n.|快乐
plenty|n.|大量
plot|n.|情节
plug|n./v.|插头
plus|prep./adj.|加
pocket|n.|口袋
poem|n.|诗
poet|n.|诗人
poetry|n.|诗歌
point|n./v.|点；指向
poison|n./v.|毒药
poisonous|adj.|有毒的
polar|adj.|极地的
pole|n.|杆
police|n.|警察
policeman|n.|警察
policy|n.|政策
polish|v./n.|擦亮
polite|adj.|有礼貌的
political|adj.|政治的
politics|n.|政治
pollute|v.|污染
pollution|n.|污染
pond|n.|池塘
pool|n.|水池
poor|adj.|穷的
pop|adj.|流行的
popular|adj.|受欢迎的
popularity|n.|流行
population|n.|人口
pork|n.|猪肉
port|n.|港口
portable|adj.|便携的
porter|n.|搬运工
portion|n.|部分
portrait|n.|肖像
Portuguese|adj./n.|葡萄牙的
position|n.|位置
positive|adj.|积极的
possess|v.|拥有
possession|n.|拥有
possibility|n.|可能性
possible|adj.|可能的
possibly|adv.|可能地
post|n./v.|邮件；帖子
postcard|n.|明信片
poster|n.|海报
postpone|v.|推迟
pot|n.|锅
potato|n.|土豆
potential|adj./n.|潜在的
pound|n.|磅
pour|v.|倒
poverty|n.|贫穷
powder|n.|粉末
power|n.|力量
powerful|adj.|强大的
practical|adj.|实际的
practice|n./v.|练习
praise|v./n.|赞扬
pray|v.|祈祷
precious|adj.|珍贵的
precise|adj.|精确的
predict|v.|预测
prefer|v.|更喜欢
preference|n.|偏好
pregnant|adj.|怀孕的
prejudice|n.|偏见
preparation|n.|准备
prepare|v.|准备
preposition|n.|介词
prescription|n.|处方
presence|n.|存在
present|adj./n./v.|现在的；礼物；呈现
presentation|n.|展示
preserve|v.|保护
president|n.|总统
press|v./n.|按
pressure|n.|压力
pretend|v.|假装
pretty|adj./adv.|漂亮的
prevent|v.|阻止
previous|adj.|以前的
price|n.|价格
pride|n.|骄傲
priest|n.|牧师
primary|adj.|主要的
prime|adj.|主要的
prince|n.|王子
princess|n.|公主
principal|adj./n.|主要的
principle|n.|原则
print|v./n.|打印
printer|n.|打印机
prior|adj.|优先的
priority|n.|优先
prison|n.|监狱
prisoner|n.|囚犯
private|adj.|私人的
prize|n.|奖品
probably|adv.|可能
problem|n.|问题
procedure|n.|程序
process|n./v.|过程
produce|v.|生产
producer|n.|生产者
product|n.|产品
production|n.|生产
profession|n.|职业
professional|adj.|专业的
professor|n.|教授
profile|n.|简介
profit|n.|利润
program|n.|程序
programmer|n.|程序员
progress|n./v.|进步
prohibit|v.|禁止
project|n./v.|项目
promise|n./v.|承诺
promote|v.|促进
prompt|adj./v.|迅速的
pronoun|n.|代词
pronounce|v.|发音
pronunciation|n.|发音
proof|n.|证据
proper|adj.|适当的
properly|adv.|适当地
property|n.|财产
proposal|n.|提议
propose|v.|提议
prospect|n.|前景
protect|v.|保护
protection|n.|保护
protein|n.|蛋白质
protest|v./n.|抗议
proud|adj.|骄傲的
prove|v.|证明
provide|v.|提供
province|n.|省
psychology|n.|心理学
pub|n.|酒吧
public|adj./n.|公共的
publish|v.|出版
pull|v./n.|拉
pulse|n.|脉搏
pump|n./v.|泵
punctual|adj.|准时的
punish|v.|惩罚
punishment|n.|惩罚
pupil|n.|学生
puppy|n.|小狗
purchase|v./n.|购买
pure|adj.|纯的
purple|adj.|紫色的
purpose|n.|目的
purse|n.|钱包
push|v./n.|推
put|v.|放
puzzle|n./v.|谜题
qualification|n.|资格
qualify|v.|使有资格
quality|n.|质量
quantity|n.|数量
quarrel|n./v.|争吵
quarter|n.|四分之一
queen|n.|女王
queer|adj.|奇怪的
question|n./v.|问题
queue|n./v.|排队
quick|adj.|快的
quickly|adv.|快地
quiet|adj.|安静的
quietly|adv.|安静地
quit|v.|辞职
quite|adv.|相当
quiz|n.|测验
quotation|n.|引用
quote|v.|引用
rabbit|n.|兔子
race|n./v.|赛跑
racial|adj.|种族的
rack|n.|架子
radar|n.|雷达
radiation|n.|辐射
radio|n.|收音机
rag|n.|破布
rail|n.|铁轨
railway|n.|铁路
rain|n./v.|雨
rainbow|n.|彩虹
rainy|adj.|下雨的
raise|v.|举起
range|n./v.|范围
rank|n./v.|排名
rapid|adj.|迅速的
rare|adj.|稀有的
rarely|adv.|很少
rat|n.|老鼠
rate|n.|比率
rather|adv.|宁愿
raw|adj.|生的
ray|n.|光线
razor|n.|剃刀
reach|v.|到达
react|v.|反应
reaction|n.|反应
read|v.|读
reader|n.|读者
reading|n.|阅读
ready|adj.|准备好的
real|adj.|真实的
reality|n.|现实
realize|v.|意识到
really|adv.|真正地
reason|n./v.|原因
reasonable|adj.|合理的
recall|v.|回忆
receipt|n.|收据
receive|v.|收到
recent|adj.|最近的
recently|adv.|最近
reception|n.|接待
recipe|n.|食谱
recite|v.|背诵
recognize|v.|认出
recommend|v.|推荐
record|n./v.|记录
recorder|n.|录音机
recover|v.|恢复
recovery|n.|恢复
recreation|n.|娱乐
recycle|v.|回收
red|adj.|红色的
reduce|v.|减少
reduction|n.|减少
refer|v.|参考
reference|n.|参考
reflect|v.|反映
reflection|n.|反映
reform|n./v.|改革
refresh|v.|刷新
refrigerator|n.|冰箱
refuge|n.|避难
refugee|n.|难民
refuse|v.|拒绝
regard|v./n.|认为
regarding|prep.|关于
regional|adj.|地区的
register|v./n.|登记
regret|v./n.|后悔
regular|adj.|规律的
regularly|adv.|规律地
regulate|v.|管理
regulation|n.|规定
reject|v.|拒绝
relate|v.|有关
relation|n.|关系
relationship|n.|关系
relative|n./adj.|亲戚
relax|v.|放松
relaxation|n.|放松
release|v./n.|释放
relevant|adj.|相关的
reliable|adj.|可靠的
relief|n.|救济
relieve|v.|减轻
religion|n.|宗教
religious|adj.|宗教的
rely|v.|依赖
remain|v.|保持
remark|n./v.|评论
remarkable|adj.|卓越的
remember|v.|记得
remind|v.|提醒
remote|adj.|偏远的
remove|v.|移除
rent|n./v.|租金
repair|v./n.|修理
repeat|v.|重复
repeatedly|adv.|反复地
replace|v.|替换
reply|n./v.|回复
report|n./v.|报告
reporter|n.|记者
represent|v.|代表
representative|n./adj.|代表
reputation|n.|声誉
request|n./v.|请求
require|v.|需要
requirement|n.|要求
rescue|v./n.|营救
research|n./v.|研究
researcher|n.|研究者
reserve|v./n.|储备
resident|n.|居民
resign|v.|辞职
resist|v.|抵抗
resistance|n.|抵抗
resolve|v.|解决
resource|n.|资源
respect|n./v.|尊重
respond|v.|回应
response|n.|回应
responsibility|n.|责任
responsible|adj.|负责任的
rest|n./v.|休息
restaurant|n.|餐厅
restore|v.|恢复
restrict|v.|限制
result|n./v.|结果
retell|v.|复述
retire|v.|退休
return|v./n.|返回
reveal|v.|揭示
revenue|n.|收入
review|n./v.|回顾
revolution|n.|革命
reward|n./v.|奖励
rhyme|n./v.|押韵
rib|n.|肋骨
ribbon|n.|丝带
rice|n.|米饭
rich|adj.|富的
ride|v./n.|骑
right|adj./adv./n.|对的；右边
ring|n./v.|戒指；按铃
rise|v./n.|升起
risk|n./v.|风险
rival|n./adj.|竞争对手
river|n.|河
road|n.|路
rob|v.|抢劫
robot|n.|机器人
rock|n./v.|岩石
rocket|n.|火箭
role|n.|角色
roll|v./n.|滚动
Roman|adj./n.|罗马的
romantic|adj.|浪漫的
roof|n.|屋顶
room|n.|房间
root|n.|根
rope|n.|绳子
rose|n.|玫瑰
rough|adj.|粗糙的
round|adj./adv./prep.|圆的
route|n.|路线
routine|n.|常规
row|n./v.|排
royal|adj.|皇家的
rubber|n.|橡胶
rubbish|n.|垃圾
rude|adj.|粗鲁的
rug|n.|地毯
ruin|n./v.|毁灭
rule|n./v.|规则
ruler|n.|尺；统治者
run|v.|跑
rural|adj.|农村的
rush|v./n.|冲
sad|adj.|悲伤的
safe|adj.|安全的
safety|n.|安全
sail|v./n.|航行
sailor|n.|水手
salad|n.|沙拉
salary|n.|薪水
sale|n.|出售
salesman|n.|推销员
salt|n.|盐
salty|adj.|咸的
same|adj./pron.|相同的
sample|n.|样品
sand|n.|沙
sandwich|n.|三明治
satellite|n.|卫星
satisfaction|n.|满意
satisfy|v.|满足
Saturday|n.|星期六
sauce|n.|酱汁
saucer|n.|茶碟
sausage|n.|香肠
save|v.|拯救；节省
saving|n.|储蓄
say|v.|说
saying|n.|谚语
scale|n.|规模
scan|v.|扫描
scarce|adj.|稀少的
scared|adj.|害怕的
scene|n.|场景
scenery|n.|风景
schedule|n./v.|时间表
scheme|n.|计划
scholar|n.|学者
scholarship|n.|奖学金
school|n.|学校
science|n.|科学
scientific|adj.|科学的
scientist|n.|科学家
scissors|n.|剪刀
scold|v.|责骂
scooter|n.|踏板车
score|n./v.|得分
Scotland|n.|苏格兰
Scottish|adj.|苏格兰的
scratch|v./n.|抓
scream|v./n.|尖叫
screen|n.|屏幕
screw|n./v.|螺丝
sculpture|n.|雕塑
sea|n.|海
seal|n./v.|印章；密封
search|v./n.|搜索
season|n.|季节
seat|n./v.|座位
second|num./adj./n.|第二；秒
secondary|adj.|中级的
secret|adj./n.|秘密
secretary|n.|秘书
section|n.|部分
sector|n.|部门
secure|adj.|安全的
security|n.|安全
see|v.|看见
seed|n.|种子
seek|v.|寻找
seem|v.|似乎
seize|v.|抓住
seldom|adv.|很少
select|v.|选择
selection|n.|选择
self|n.|自己
selfish|adj.|自私的
sell|v.|卖
semester|n.|学期
send|v.|发送
senior|adj./n.|年长的
sense|n./v.|感觉
sensitive|adj.|敏感的
sentence|n.|句子
separate|adj./v.|分开的
September|n.|九月
series|n.|系列
serious|adj.|严肃的
seriously|adv.|认真地
servant|n.|仆人
serve|v.|服务
service|n.|服务
session|n.|会议
set|v./n.|设置；一套
settle|v.|解决
settlement|n.|解决
seven|num.|七
seventeen|num.|十七
seventy|num.|七十
several|adj.|几个
severe|adj.|严重的
sew|v.|缝
sex|n.|性别
shabby|adj.|破旧的
shade|n.|阴凉处
shadow|n.|影子
shake|v./n.|摇动
shall|v.|将要
shallow|adj.|浅的
shame|n.|羞耻
shampoo|n.|洗发水
shape|n./v.|形状
share|v./n.|分享
shark|n.|鲨鱼
sharp|adj.|锋利的
shave|v.|刮
she|pron.|她
sheep|n.|羊
sheet|n.|床单
shelf|n.|架子
shell|n.|壳
shelter|n./v.|庇护
shield|n./v.|盾牌
shift|v./n.|转移
shine|v.|照耀
ship|n./v.|船
shirt|n.|衬衫
shock|n./v.|震惊
shoe|n.|鞋
shoot|v.|射击
shop|n./v.|商店
shopping|n.|购物
shore|n.|海岸
short|adj.|短的
shortage|n.|短缺
shortly|adv.|不久
shorts|n.|短裤
shot|n.|射击
should|v.|应该
shoulder|n.|肩膀
shout|v./n.|喊叫
show|v./n.|展示
shower|n./v.|淋浴
shrink|v.|收缩
shut|v.|关
shuttle|n.|梭子
shy|adj.|害羞的
sick|adj.|病的
side|n.|边
sideways|adv.|向旁边
sigh|n./v.|叹息
sight|n.|视觉
sightseeing|n.|观光
sign|n./v.|标志
signal|n./v.|信号
signature|n.|签名
significance|n.|重要性
significant|adj.|重要的
silence|n.|沉默
silent|adj.|沉默的
silk|n.|丝绸
silly|adj.|傻的
silver|n./adj.|银
similar|adj.|相似的
similarity|n.|相似性
simple|adj.|简单的
simply|adv.|简单地
since|conj./prep.|自从
sincere|adj.|真诚的
sing|v.|唱
singer|n.|歌手
single|adj.|单一的
sink|v./n.|下沉
sir|n.|先生
sister|n.|姐妹
sit|v.|坐
site|n.|地点
situation|n.|情况
six|num.|六
sixteen|num.|十六
sixty|num.|六十
size|n.|大小
skate|v.|滑冰
ski|v.|滑雪
skill|n.|技能
skilled|adj.|熟练的
skin|n.|皮肤
skirt|n.|裙子
sky|n.|天空
skyscraper|n.|摩天大楼
slave|n.|奴隶
sleep|v./n.|睡觉
slice|n./v.|薄片
slide|v./n.|滑动
slight|adj.|轻微的
slim|adj.|苗条的
slip|v.|滑倒
slope|n.|斜坡
slow|adj./adv.|慢的
slowly|adv.|慢地
small|adj.|小的
smart|adj.|聪明的
smell|n./v.|闻
smile|n./v.|微笑
smoke|n./v.|烟
smooth|adj.|光滑的
snack|n.|零食
snake|n.|蛇
snap|v.|折断
snow|n./v.|雪
so|adv./conj.|所以
soap|n.|肥皂
soccer|n.|足球
social|adj.|社会的
society|n.|社会
sock|n.|袜子
soda|n.|苏打
sofa|n.|沙发
soft|adj.|软的
software|n.|软件
soil|n.|土壤
soldier|n.|士兵
solid|adj./n.|固体的
solution|n.|解决方案
solve|v.|解决
some|adj./pron.|一些
somebody|pron.|某人
somehow|adv.|以某种方式
someone|pron.|某人
something|pron.|某事
sometimes|adv.|有时
somewhere|adv.|某处
son|n.|儿子
song|n.|歌曲
soon|adv.|很快
sore|adj.|疼痛的
sorry|adj.|抱歉的
sort|n./v.|种类
soul|n.|灵魂
sound|n./v.|声音
soup|n.|汤
sour|adj.|酸的
source|n.|来源
south|n./adj.|南
southern|adj.|南方的
souvenir|n.|纪念品
space|n.|空间
spaceship|n.|宇宙飞船
spade|n.|铲子
Spain|n.|西班牙
Spanish|adj./n.|西班牙的
spare|adj./v.|空闲的
speak|v.|说
speaker|n.|演讲者
special|adj.|特别的
specialist|n.|专家
specific|adj.|具体的
speech|n.|演讲
speed|n./v.|速度
spell|v.|拼写
spelling|n.|拼写
spend|v.|花费
spider|n.|蜘蛛
spirit|n.|精神
spiritual|adj.|精神的
spit|v.|吐
splash|v.|溅
split|v.|分裂
spoil|v.|损坏
sponsor|n./v.|赞助
spoon|n.|勺子
sport|n.|运动
spot|n./v.|地点
spread|v.|传播
spring|n.|春天
spy|n.|间谍
square|n./adj.|广场；正方形
stable|adj.|稳定的
stadium|n.|体育场
staff|n.|员工
stage|n.|舞台
stair|n.|楼梯
stamp|n.|邮票
stand|v./n.|站立
standard|n./adj.|标准
star|n.|星
stare|v.|凝视
start|v./n.|开始
state|n./v.|状态
statement|n.|声明
station|n.|车站
statue|n.|雕像
status|n.|地位
stay|v./n.|停留
steady|adj.|稳定的
steal|v.|偷
steam|n.|蒸汽
steel|n.|钢
steep|adj.|陡峭的
step|n./v.|步骤
stick|n./v.|棍子；坚持
stiff|adj.|僵硬的
still|adv./adj.|仍然；静止的
sting|v./n.|刺
stir|v.|搅拌
stitch|n./v.|针脚
stocking|n.|长袜
stomach|n.|胃
stone|n.|石头
stop|v./n.|停止
store|n./v.|商店
storey|n.|楼层
storm|n.|暴风雨
story|n.|故事
stove|n.|炉子
straight|adj./adv.|直的
strange|adj.|奇怪的
stranger|n.|陌生人
strategy|n.|策略
straw|n.|稻草
strawberry|n.|草莓
stream|n.|小溪
street|n.|街道
strength|n.|力量
strengthen|v.|加强
stress|n./v.|压力
stretch|v.|伸展
strict|adj.|严格的
strike|v./n.|罢工
string|n.|绳子
strip|n./v.|条
stripe|n.|条纹
stroke|n./v.|中风；抚摸
strong|adj.|强壮的
structure|n.|结构
struggle|v./n.|挣扎
student|n.|学生
studio|n.|工作室
study|v./n.|学习
stuff|n./v.|东西
stupid|adj.|愚蠢的
style|n.|风格
subject|n./adj.|科目
submit|v.|提交
substance|n.|物质
substitute|n./v.|替代品
subtract|v.|减
suburb|n.|郊区
subway|n.|地铁
succeed|v.|成功
success|n.|成功
successful|adj.|成功的
such|adj./pron.|这样的
suck|v.|吸
sudden|adj.|突然的
suddenly|adv.|突然
suffer|v.|遭受
sufficient|adj.|足够的
sugar|n.|糖
suggest|v.|建议
suggestion|n.|建议
suit|n./v.|西装；适合
suitable|adj.|合适的
suitcase|n.|手提箱
sum|n.|总和
summarize|v.|总结
summary|n.|摘要
summer|n.|夏天
sun|n.|太阳
Sunday|n.|星期日
sunlight|n.|阳光
sunny|adj.|晴朗的
sunrise|n.|日出
sunset|n.|日落
sunshine|n.|阳光
super|adj.|超级的
superior|adj.|优越的
supermarket|n.|超市
supper|n.|晚餐
supply|v./n.|供应
support|v./n.|支持
suppose|v.|假设
sure|adj.|确定的
surf|v.|冲浪
surface|n.|表面
surgeon|n.|外科医生
surgery|n.|手术
surprise|n./v.|惊讶
surround|v.|围绕
surrounding|adj.|周围的
survey|n./v.|调查
survival|n.|生存
survive|v.|幸存
suspect|v./n.|怀疑
suspend|v.|暂停
suspicion|n.|怀疑
swallow|v./n.|吞咽
swan|n.|天鹅
swap|v.|交换
swear|v.|发誓
sweat|n./v.|汗
sweater|n.|毛衣
sweep|v.|扫
sweet|adj./n.|甜的
swell|v.|膨胀
swift|adj.|迅速的
swim|v.|游泳
swing|v./n.|摇摆
switch|n./v.|开关
symbol|n.|象征
sympathy|n.|同情
symphony|n.|交响乐
symptom|n.|症状
system|n.|系统
table|n.|桌子
tablet|n.|药片
tag|n.|标签
tail|n.|尾巴
tailor|n.|裁缝
take|v.|拿
tale|n.|故事
talent|n.|才能
talk|v./n.|谈话
tall|adj.|高的
tank|n.|坦克；水箱
tap|n./v.|水龙头
tape|n.|磁带
target|n./v.|目标
task|n.|任务
taste|n./v.|味道
tax|n.|税
taxi|n.|出租车
tea|n.|茶
teach|v.|教
teacher|n.|老师
team|n.|团队
tear|n./v.|眼泪；撕
technical|adj.|技术的
technique|n.|技术
technology|n.|技术
teenager|n.|青少年
telegram|n.|电报
telephone|n.|电话
telescope|n.|望远镜
television|n.|电视
tell|v.|告诉
temper|n.|脾气
temperature|n.|温度
temple|n.|寺庙
temporary|adj.|临时的
tempt|v.|诱惑
ten|num.|十
tend|v.|倾向于
tendency|n.|倾向
tennis|n.|网球
tense|adj./n.|紧张的；时态
tension|n.|紧张
tent|n.|帐篷
term|n.|学期
terminal|n./adj.|终端
terrible|adj.|可怕的
territory|n.|领土
terror|n.|恐怖
test|n./v.|测试
text|n.|文本
textbook|n.|教科书
than|conj.|比
thank|v./n.|感谢
that|pron./adj./conj.|那个
the|art.|这
theater|n.|剧院
theft|n.|盗窃
their|pron.|他们的
theirs|pron.|他们的
them|pron.|他们
themselves|pron.|他们自己
then|adv.|然后
theory|n.|理论
there|adv.|那里
therefore|adv.|因此
these|pron./adj.|这些
they|pron.|他们
thick|adj.|厚的
thief|n.|小偷
thin|adj.|薄的
thing|n.|事情
think|v.|想
third|num./adj.|第三
thirsty|adj.|渴的
thirteen|num.|十三
thirty|num.|三十
this|pron./adj.|这个
thorough|adj.|彻底的
those|pron./adj.|那些
though|conj.|虽然
thought|n.|想法
thousand|num.|千
thread|n.|线
threat|n.|威胁
threaten|v.|威胁
three|num.|三
throat|n.|喉咙
through|prep./adv.|通过
throughout|prep./adv.|贯穿
throw|v.|扔
thumb|n.|拇指
thunder|n./v.|雷
Thursday|n.|星期四
thus|adv.|因此
ticket|n.|票
tide|n.|潮汐
tidy|adj.|整洁的
tie|n./v.|领带；系
tiger|n.|老虎
tight|adj.|紧的
till|prep./conj.|直到
time|n.|时间
timetable|n.|时间表
tiny|adj.|微小的
tip|n.|尖端；小费
tired|adj.|累的
tissue|n.|纸巾
title|n.|标题
to|prep.|到
toast|n./v.|烤面包
tobacco|n.|烟草
today|n./adv.|今天
toe|n.|脚趾
together|adv.|一起
toilet|n.|厕所
tomato|n.|西红柿
tomb|n.|坟墓
tomorrow|n./adv.|明天
ton|n.|吨
tone|n.|语气
tongue|n.|舌头
tonight|n./adv.|今晚
too|adv.|也；太
tool|n.|工具
tooth|n.|牙齿
toothache|n.|牙痛
toothbrush|n.|牙刷
toothpaste|n.|牙膏
top|n./adj.|顶部
topic|n.|主题
torch|n.|手电筒
tornado|n.|龙卷风
total|adj./n.|总的
totally|adv.|完全
touch|v./n.|触摸
tough|adj.|坚韧的
tour|n./v.|旅游
tourism|n.|旅游业
tourist|n.|游客
toward|prep.|朝
towel|n.|毛巾
tower|n.|塔
town|n.|镇
toy|n.|玩具
trace|n./v.|痕迹
track|n./v.|轨道
trade|n./v.|贸易
tradition|n.|传统
traditional|adj.|传统的
traffic|n.|交通
tragedy|n.|悲剧
train|n./v.|火车；训练
training|n.|训练
transfer|v.|转移
transform|v.|改变
translate|v.|翻译
translation|n.|翻译
translator|n.|翻译者
transport|v./n.|运输
transportation|n.|交通
trap|n./v.|陷阱
travel|v./n.|旅行
tray|n.|托盘
treasure|n.|宝藏
treat|v./n.|对待
treatment|n.|治疗
tree|n.|树
tremble|v.|颤抖
tremendous|adj.|巨大的
trend|n.|趋势
trial|n.|审判
triangle|n.|三角形
trick|n./v.|诡计
trip|n.|旅行
triumph|n.|胜利
troops|n.|军队
tropical|adj.|热带的
trouble|n./v.|麻烦
trousers|n.|裤子
truck|n.|卡车
true|adj.|真的
truly|adv.|真正地
trumpet|n.|喇叭
trust|v./n.|信任
truth|n.|真相
try|v.|尝试
T-shirt|n.|T恤
tube|n.|管
Tuesday|n.|星期二
tunnel|n.|隧道
turkey|n.|火鸡
turn|v./n.|转
TV|n.|电视
twelve|num.|十二
twenty|num.|二十
twice|adv.|两次
twin|n.|双胞胎
twist|v./n.|扭曲
two|num.|二
type|n./v.|类型
typewriter|n.|打字机
typical|adj.|典型的
tyre|n.|轮胎
ugly|adj.|丑的
umbrella|n.|雨伞
unable|adj.|不能的
uncle|n.|叔叔
under|prep.|在...下
undergo|v.|经历
underground|adj./n.|地下的
underline|v.|下划线
understand|v.|理解
understanding|n.|理解
underwear|n.|内衣
unemployment|n.|失业
unfair|adj.|不公平的
unfortunately|adv.|不幸地
unhappy|adj.|不快乐的
uniform|n.|制服
union|n.|联盟
unique|adj.|独特的
unit|n.|单位
unite|v.|团结
united|adj.|联合的
universal|adj.|普遍的
universe|n.|宇宙
university|n.|大学
unknown|adj.|未知的
unless|conj.|除非
unlike|prep./adj.|不像
unlikely|adj.|不太可能的
until|prep./conj.|直到
unusual|adj.|不寻常的
up|adv./prep.|向上
update|v./n.|更新
upon|prep.|在...上
upper|adj.|上面的
upset|adj./v.|心烦的
upstairs|adv.|楼上
urban|adj.|城市的
urge|v./n.|催促
urgent|adj.|紧急的
us|pron.|我们
USB|n.|U盘
use|v./n.|使用
used|adj.|习惯的
useful|adj.|有用的
useless|adj.|无用的
user|n.|用户
usual|adj.| usual
usually|adv.|通常
vacant|adj.|空的
vacation|n.|假期
vacuum|n.|真空
vague|adj.|模糊的
vain|adj.|虚荣的
valid|adj.|有效的
valley|n.|山谷
valuable|adj.|有价值的
value|n./v.|价值
van|n.|货车
vanish|v.|消失
variety|n.|多样性
various|adj.|各种各样的
vary|v.|变化
vast|adj.|巨大的
vegetable|n.|蔬菜
vehicle|n.|车辆
venture|n./v.|冒险
verb|n.|动词
version|n.|版本
very|adv.|非常
vest|n.|背心
via|prep.|通过
vice|n.|恶习
victim|n.|受害者
victory|n.|胜利
video|n.|视频
view|n./v.|观点
village|n.|村庄
villager|n.|村民
violence|n.|暴力
violent|adj.|暴力的
violin|n.|小提琴
virtual|adj.|虚拟的
virtue|n.|美德
virus|n.|病毒
visa|n.|签证
visible|adj.|可见的
vision|n.|视力
visit|v./n.|参观
visitor|n.|访客
vital|adj.|至关重要的
vitamin|n.|维生素
vivid|adj.|生动的
vocabulary|n.|词汇
voice|n.|声音
volcano|n.|火山
volleyball|n.|排球
volume|n.|体积；音量
voluntary|adj.|自愿的
volunteer|n./v.|志愿者
vote|v./n.|投票
voyage|n.|航行
wage|n.|工资
waist|n.|腰
wait|v.|等待
waiter|n.|服务员
waitress|n.|女服务员
wake|v.|醒来
walk|v./n.|走
wall|n.|墙
wallet|n.|钱包
wander|v.|漫游
want|v.|想要
war|n.|战争
warm|adj.|温暖的
warn|v.|警告
warning|n.|警告
wash|v./n.|洗
waste|n./v.|浪费
watch|v./n.|观看
water|n./v.|水
waterfall|n.|瀑布
watermelon|n.|西瓜
wave|n./v.|波浪
way|n.|路
we|pron.|我们
weak|adj.|弱的
weakness|n.|弱点
wealth|n.|财富
wealthy|adj.|富有的
weapon|n.|武器
wear|v.|穿
weather|n.|天气
weave|v.|编织
web|n.|网络
website|n.|网站
wedding|n.|婚礼
Wednesday|n.|星期三
weed|n.|杂草
week|n.|周
weekday|n.|工作日
weekend|n.|周末
weekly|adj./adv.|每周的
weep|v.|哭泣
weigh|v.|称重
weight|n.|重量
welcome|adj./v./n.|欢迎
welfare|n.|福利
well|adv./n.|好；井
well-known|adj.|著名的
west|n./adj.|西
western|adj.|西方的
wet|adj.|湿的
whale|n.|鲸鱼
what|pron./adj.|什么
whatever|pron./adj.|无论什么
wheat|n.|小麦
wheel|n.|轮子
wheelchair|n.|轮椅
when|adv./conj.|当...时
whenever|conj.|每当
where|adv./conj.|哪里
wherever|conj.|无论哪里
whether|conj.|是否
which|pron./adj.|哪个
while|conj./n.|当...时
whisper|v./n.|低语
whistle|n./v.|口哨
white|adj.|白色的
who|pron.|谁
whoever|pron.|无论谁
whole|adj./n.|整个的
whom|pron.|谁(宾格)
whose|pron.|谁的
why|adv./conj.|为什么
wide|adj.|宽的
widely|adv.|广泛地
wife|n.|妻子
wild|adj.|野生的
wildlife|n.|野生动物
will|v./n.|将；意志
willing|adj.|愿意的
win|v.|赢
wind|n./v.|风；缠绕
window|n.|窗户
windy|adj.|有风的
wine|n.|酒
wing|n.|翅膀
winner|n.|获胜者
winter|n.|冬天
wipe|v.|擦
wire|n.|电线
wisdom|n.|智慧
wise|adj.|明智的
wish|v./n.|希望
with|prep.|和...一起
withdraw|v.|撤回
within|prep.|在...内
without|prep.|没有
witness|n./v.|证人
wolf|n.|狼
woman|n.|女人
wonder|v./n.|想知道
wonderful|adj.|奇妙的
wood|n.|木头
wooden|adj.|木制的
woods|n.|树林
wool|n.|羊毛
word|n.|单词
work|v./n.|工作
worker|n.|工人
workshop|n.|车间
world|n.|世界
worldwide|adj.|全球的
worm|n.|虫
worried|adj.|担心的
worry|v./n.|担心
worse|adj./adv.|更坏的
worship|n./v.|崇拜
worst|adj./adv.|最坏的
worth|adj./n.|值得
worthwhile|adj.|值得的
would|v.|将
wound|n./v.|伤口
wrap|v.|包
wrist|n.|手腕
write|v.|写
writer|n.|作家
writing|n.|写作
written|adj.|书面的
wrong|adj./adv.|错误的
X-ray|n.|X光
yard|n.|院子
year|n.|年
yearly|adj./adv.|每年的
yellow|adj.|黄色的
yes|adv.|是
yesterday|n./adv.|昨天
yet|adv./conj.|还
yogurt|n.|酸奶
young|adj.|年轻的
youngster|n.|年轻人
your|pron.|你的
yours|pron.|你的
yourself|pron.|你自己
youth|n.|青春
yummy|adj.|美味的
zebra|n.|斑马
zero|num./n.|零
zip|n./v.|拉链
zone|n.|区域
zoo|n.|动物园
"""

def generate_js():
    lines = WORDS_RAW.strip().split('\n')
    words = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        parts = line.split('|')
        if len(parts) >= 3:
            word = parts[0].strip()
            pos = parts[1].strip()
            meaning = '|'.join(parts[2:]).strip()
            if word and pos and meaning:
                words.append([word, pos, meaning])

    # Generate JavaScript
    js_lines = []
    js_lines.append('/**')
    js_lines.append(' * CET-4 额外词汇数据 (A-Z)')
    js_lines.append(' * 格式: [word, pos, meaning]')
    js_lines.append(' * 与 data.js 中的 CET4_WORDS 合并使用，已有单词自动跳过')
    js_lines.append(' */')
    js_lines.append('const CET4_EXTRA_WORDS = [')
    for w in words:
        js_lines.append('  ["%s","%s","%s"],' % (
            w[0].replace('"', '\\"'),
            w[1].replace('"', '\\"'),
            w[2].replace('"', '\\"')
        ))
    js_lines.append('];')
    js_lines.append('')
    js_lines.append('// 合并到 CET4_WORDS')
    js_lines.append('if (typeof CET4_WORDS !== \'undefined\') {')
    js_lines.append('  var _existing = new Set(CET4_WORDS.map(function(w) { return w.word; }));')
    js_lines.append('  CET4_EXTRA_WORDS.forEach(function(item) {')
    js_lines.append('    if (!_existing.has(item[0])) {')
    js_lines.append('      CET4_WORDS.push({ word: item[0], phonetic: \'\', pos: item[1], meaning: item[2], example: \'\' });')
    js_lines.append('    }')
    js_lines.append('  });')
    js_lines.append('}')
    js_lines.append('')
    js_lines.append('console.log(\'CET4_EXTRA_WORDS loaded:\', CET4_EXTRA_WORDS.length, \'additional words,\', CET4_WORDS.length, \'total\');')

    return '\n'.join(js_lines)

if __name__ == '__main__':
    js_content = generate_js()
    with open('js/cet4_extra.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    # Count words
    lines = WORDS_RAW.strip().split('\n')
    count = sum(1 for l in lines if l.strip() and '|' in l)
    print(f'Generated {count} extra words')
    print(f'Combined with existing 288 = {count + 288} total words')
    print('File: js/cet4_extra.js')
